---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 01.04.2020 7:40
---
do



    local PlayerCameraState = 0
    local PlayerCameraSetup = 0
    local PlayerCameraZoomMode = nil





    function LockCameraForPlayer(player_id)
        PlayerCameraState[player_id] = true
        CameraSetupSetDestPosition(PlayerCameraSetup[player_id], GetUnitX(PlayerHero[player_id]), GetUnitY(PlayerHero[player_id]), 0.01)
    end


    function InitPlayerCamera()

        PlayerCameraState = {}
        PlayerCameraSetup = {}
        PlayerCameraZoomMode = {}
        local trigger = CreateTrigger()

        for i = 1, 6 do
            PlayerCameraSetup[i] = CreateCameraSetup()
            CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_ANGLE_OF_ATTACK, 304., 0)
            CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_TARGET_DISTANCE, 1800., 0)
            CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_ROTATION, 90., 0)
            CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_FIELD_OF_VIEW, 70., 0)
            CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_FARZ, 5000., 0)
            BlzTriggerRegisterPlayerKeyEvent(trigger, Player(i-1), OSKEY_Z, 0, true)
        end

        local timer = CreateTimer()
        TimerStart(timer, 0.025, true, function ()

            for i = 1, 6 do
                if PlayerCameraState[i] and PlayerHero[i] then
                    if PlayerCameraZoomMode[i] then
                        CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_TARGET_DISTANCE, 500., 0.5)
                        CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_ZOFFSET, 85., 0.5)
                        CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_ANGLE_OF_ATTACK, 320., 0.5)
                    else
                        CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_TARGET_DISTANCE, 1800., 0.07)
                        CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_ANGLE_OF_ATTACK, 304., 0.07)
                        CameraSetupSetField(PlayerCameraSetup[i], CAMERA_FIELD_ZOFFSET, GetZ(GetUnitX(PlayerHero[i]), GetUnitY(PlayerHero[i])) * 0.1, 0.07)
                    end

                    CameraSetupSetDestPosition(PlayerCameraSetup[i], GetUnitX(PlayerHero[i]), GetUnitY(PlayerHero[i])+55., 0.07)
                    if GetLocalPlayer() == Player(i-1) then CameraSetupApply(PlayerCameraSetup[i], true, true) end

                end
            end

        end)


        TriggerAddAction(trigger, function()
            local player = GetPlayerId(GetTriggerPlayer())+1
                if PlayerCameraZoomMode[player] then
                    PlayerCameraZoomMode[player] = false
                else
                    PlayerCameraZoomMode[player] = true
                    DisplayTextToPlayer(Player(player-1), 0.,0., GetLocalString("Нажата клавиша [Z]. Режим приближения.", "[Z] key has been pressed. Zoom mode."))
                end
        end)


        RegisterTestCommand("cam", function ()
            PlayerCameraState[1] = false
            Cheat("iseedeadpeople")
        end)

    end

end