---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 19.01.2020 17:58
---
do


    local UNIT_DROP_LIST = 0




    function DropListInit()

        InitDroplist()

    end

end