---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 15.01.2020 16:52
---
do


    local DeathTrigger


    function CreateHeroSelections()

        DeathTrigger = CreateTrigger()
        local trg = CreateTrigger()
        local barbarian_region = CreateRegion()
        RegionAddRect(barbarian_region, gg_rct_barbarian_select)

        local sorc_region = CreateRegion()
        RegionAddRect(sorc_region, gg_rct_sorceress_select)

        TriggerRegisterEnterRegionSimple(trg, barbarian_region)
        TriggerRegisterEnterRegionSimple(trg, sorc_region)

        TriggerAddAction(trg, function ()
            local region = GetTriggeringRegion()
            local id
            local player_id = GetPlayerId(GetOwningPlayer(GetTriggerUnit()))


                if region == barbarian_region then
                    id = FourCC("HBRB")
                else
                    id = FourCC("HSRC")
                end

                local hero = CreateUnit(Player(player_id), id, GetRectCenterX(gg_rct_starting_location) , GetRectCenterY(gg_rct_starting_location), 270.)
                RemoveUnit(GetTriggerUnit())


                TimerStart(CreateTimer(), 0.1, false, function()
                    player_id = player_id + 1
                    PlayerHero[player_id] = hero

                    TriggerRegisterDeathEvent(DeathTrigger, hero)


                    DrawStatsPanelInterface(player_id)
                    DrawInventoryFrames(player_id, hero)
                    DrawSkillPanel(player_id)
                    DrawShopFrames(player_id)

                    AddToPanel(hero, player_id)
                    AddPointsToPlayer(player_id, 5)

                    if GetLocalPlayer() == Player(player_id - 1) then
                        BlzFrameSetVisible(CharButton, true)
                        BlzFrameSetVisible(InventoryTriggerButton, true)
                        BlzFrameSetVisible(SkillPanelButton, true)
                        PanCameraToTimed(GetUnitX(hero), GetUnitY(hero), 0.)
                    end
                    DestroyTimer(GetExpiredTimer())
                end)


        end)


        TriggerAddAction(DeathTrigger, function ()
            local hero = GetTriggerUnit()

                TimerStart(CreateTimer(), 15., false, function()
                    ReviveHero(hero, GetRectCenterX(gg_rct_starting_location), GetRectCenterY(gg_rct_starting_location), true)
                    DestroyTimer(GetExpiredTimer())
                end)

        end)


    end

end