---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 15.01.2020 23:16
---
do

    SPAWN_POINTS = nil
    MAIN_POINT = nil
    MONSTER_PLAYER = Player(10)
    SECOND_MONSTER_PLAYER = Player(11)
    WaveGroup = CreateGroup()

    local WaveDifficultyModificator = 0.5
    local WavePlayerCountModificator = 1.

    local COMMON_MONSTER_RATE = 0.65
    local MELEE_MONSTER_CHANCE = 60.

    local WAVE_MINIMUM_COUNT = 10
    local WAVE_MAXIMUM_COUNT = 25


    local MONSTER_TAG_MELEE = 1
    local MONSTER_TAG_RANGE = 2

    MONSTERPACK_SUCCUBUS = 1
    MONSTERPACK_SKELETONS = 2
    MONSTERPACK_ZOMBIES = 3
    MONSTERPACK_DEMONS = 4
    MONSTERPACK_GHOSTS = 5
    MONSTERPACK_BANDITS = 6
    MONSTERPACK_BOSS = 10



    MONSTER_ID_ZOMBIE = "n00C"
    MONSTER_ID_ZOMBIE_MUTANT = "n00E"
    MONSTER_ID_FIEND = "u007"
    MONSTER_ID_DEMON_ASSASSIN = "u009"
    MONSTER_ID_DEMON_WIZARD = "n003"
    MONSTER_ID_DEMON_HELL_GUARD = "u00A"
    MONSTER_ID_FALLEN_ANGEL = "u008"
    MONSTER_ID_SUCCUBUS = "n002"
    MONSTER_ID_SUCCUBUS_ADVANCED = "n00B"
    MONSTER_ID_BANSHEE = "u00C"
    MONSTER_ID_GHOST = "n006"
    MONSTER_ID_VOIDWALKER = "n008"
    MONSTER_ID_ANCIENT_VOIDWALKER = "n009"
    MONSTER_ID_SKELETON = "u00D"
    MONSTER_ID_SKELETON_IMPROVED = "n00D"
    MONSTER_ID_SKELETON_ARMORED = "u00B"
    MONSTER_ID_SKELETON_ARCHER = "n005"
    MONSTER_ID_SKELETON_MAGE = "u00E"
    MONSTER_ID_SKELETON_HELL_ARCHER = "n004"
    MONSTER_ID_SKELETON_SNIPER = "n007"
    MONSTER_ID_NECROMANCER = "u00F"

    MONSTER_ID_BUTCHER = "U003"
    MONSTER_ID_BAAL = "U001"
    MONSTER_ID_MEPHISTO = "U000"
    MONSTER_ID_DEMONESS = "U006"
    MONSTER_ID_DEMONKING = "U005"
    MONSTER_ID_UNDERWORLD_QUEEN = "U002"
    MONSTER_ID_REANIMATED = "U004"



    RegisterTestCommand("endw", function()

        ForGroup(WaveGroup, function ()
            KillUnit(GetEnumUnit())
        end)

    end)





    MONSTER_EXP_RATES = {
        [MONSTER_RANK_COMMON] = 1.,
        [MONSTER_RANK_ADVANCED] = 1.25,
        [MONSTER_RANK_BOSS] = 5.,
        const_per_level = 75,
        modf_per_level = 0.02
    }

    -- attack type focus (melee/range ratio) => monster type =>


    MONSTER_LIST = {
            [MONSTERPACK_SUCCUBUS] = {
                [MONSTER_RANK_COMMON] = {
                    [MONSTER_TAG_MELEE] = {
                        { id = MONSTER_ID_SUCCUBUS, chance = 100. },
                    },
                    [MONSTER_TAG_RANGE] = {
                        { id = MONSTER_ID_SUCCUBUS_ADVANCED, chance = 100. } ,
                    }
                },
                [MONSTERPACK_BOSS] = {
                    MONSTER_ID_DEMONESS,
                    MONSTER_ID_UNDERWORLD_QUEEN
                }
            },
            [MONSTERPACK_SKELETONS] = {
                [MONSTER_RANK_COMMON] = {
                    [MONSTER_TAG_MELEE] = {
                        { id = MONSTER_ID_SKELETON_ARMORED, chance = 22.5 },
                        { id = MONSTER_ID_SKELETON_IMPROVED, chance = 32.5 },
                        { id = MONSTER_ID_SKELETON, chance = 100. },
                    },
                    [MONSTER_TAG_RANGE] = {
                        { id = MONSTER_ID_SKELETON_ARCHER, chance = 40. },
                        { id = MONSTER_ID_SKELETON_MAGE, chance = 40. },
                        { id = MONSTER_ID_NECROMANCER, chance = 100. },
                    }
                },
                [MONSTER_RANK_ADVANCED] = {
                    [MONSTER_TAG_RANGE] = {
                        { id = MONSTER_ID_SKELETON_HELL_ARCHER, chance = 50. },
                        { id = MONSTER_ID_SKELETON_SNIPER, chance = 100. },
                    }
                },
                [MONSTERPACK_BOSS] = {
                    MONSTER_ID_REANIMATED
                }
            },
            [MONSTERPACK_ZOMBIES] = {
                [MONSTER_RANK_COMMON] = {
                    [MONSTER_TAG_MELEE] = {
                        { id = MONSTER_ID_ZOMBIE, chance = 100. },
                    },
                    [MONSTER_TAG_RANGE] = {
                        { id = MONSTER_ID_NECROMANCER, chance = 100. },
                    }
                },
                [MONSTER_RANK_ADVANCED] = {
                    [MONSTER_TAG_MELEE] = {
                        { id = MONSTER_ID_ZOMBIE_MUTANT, chance = 100. },
                    }
                },
                [MONSTERPACK_BOSS] = {
                    MONSTER_ID_BUTCHER
                }
            },
            [MONSTERPACK_DEMONS] = {
                [MONSTER_RANK_COMMON] = {
                    [MONSTER_TAG_MELEE] = {
                        { id = MONSTER_ID_SKELETON_ARMORED, chance = 21.5 },
                        { id = MONSTER_ID_SUCCUBUS, chance = 33.5 },
                        { id = MONSTER_ID_FIEND, chance = 100. },
                    },
                    [MONSTER_TAG_RANGE] = {
                        { id = MONSTER_ID_NECROMANCER, chance = 23. },
                        { id = MONSTER_ID_SUCCUBUS_ADVANCED, chance = 40. },
                        { id = MONSTER_ID_VOIDWALKER, chance = 100. },
                    }
                },
                [MONSTER_RANK_ADVANCED] = {
                    [MONSTER_TAG_MELEE] = {
                        { id = MONSTER_ID_DEMON_ASSASSIN, chance = 40.5 },
                        { id = MONSTER_ID_FALLEN_ANGEL, chance = 30.5 },
                        { id = MONSTER_ID_DEMON_HELL_GUARD, chance = 100. },
                    },
                    [MONSTER_TAG_RANGE] = {
                        { id = MONSTER_ID_DEMON_WIZARD, chance = 33.5 },
                        { id = MONSTER_ID_ANCIENT_VOIDWALKER, chance = 100. },
                    }
                },
                [MONSTERPACK_BOSS] = {
                    MONSTER_ID_DEMONESS,
                    MONSTER_ID_DEMONKING,
                    MONSTER_ID_UNDERWORLD_QUEEN
                }
            },
            [MONSTERPACK_GHOSTS] = {
                [MONSTER_RANK_COMMON] = {
                    [MONSTER_TAG_RANGE] = {
                        { id = MONSTER_ID_BANSHEE, chance = 100. },
                    }
                },
                [MONSTER_RANK_ADVANCED] = {
                    [MONSTER_TAG_RANGE] = {
                        { id = MONSTER_ID_GHOST, chance = 100. },
                    }
                }
            },
            [MONSTERPACK_BOSS] = {
                MONSTER_ID_BUTCHER,
                MONSTER_ID_BAAL,
                MONSTER_ID_MEPHISTO,
                MONSTER_ID_DEMONESS ,
                MONSTER_ID_DEMONKING,
                MONSTER_ID_UNDERWORLD_QUEEN,
                MONSTER_ID_REANIMATED
            }
    }


    function GetRandomMonsterPack(rank)
        local pack = GetRandomInt(MONSTERPACK_SUCCUBUS, MONSTERPACK_GHOSTS)

            while true do
                if MONSTER_LIST[pack][rank] ~= nil then return MONSTER_LIST[pack] end
                pack = GetRandomInt(MONSTERPACK_SUCCUBUS, MONSTERPACK_GHOSTS)
            end

        return MONSTER_LIST[pack]
    end


    function GetRandomMonsterPackTag(rank, tag)
        local pack = GetRandomInt(MONSTERPACK_SUCCUBUS, MONSTERPACK_GHOSTS)
        local num = 10

            while num > 0 do
                pack = GetRandomInt(MONSTERPACK_SUCCUBUS, MONSTERPACK_GHOSTS)
                    if MONSTER_LIST[pack][rank] ~= nil and MONSTER_LIST[pack][rank][tag] ~= nil then
                        return MONSTER_LIST[pack]
                    end
                num = num - 1
            end

        return MONSTER_LIST[pack]
    end


    
    ---@param pack number
    ---@param rect rect
    ---@param amount number
    ---@param group group
    function CreateUnits_Pack(pack, rect, amount, group)
        if pack == nil then return 0 end

        local id
        local newunit

        if amount <= 0 then return end

            for i = 1, amount do
                for k = 1, #pack do if GetRandomReal(0.,100.) <= pack[k].chance then id = FourCC(pack[k].id) end end
                newunit = CreateUnit(SECOND_MONSTER_PLAYER, id, GetRandomReal(GetRectMinX(rect), GetRectMaxX(rect)), GetRandomReal(GetRectMinY(rect), GetRectMaxY(rect)), GetRandomInt(0, 359))
                GroupAddUnit(group, newunit)
            end

        return amount
    end
    

    ---@param pack number
    ---@param rect rect
    ---@param amount number
    function CreateUnits(pack, rect, amount)
        if pack == nil then return 0 end

        local id
        local newunit

        if amount <= 0 then return end

            for i = 1, amount do
                for k = 1, #pack do if GetRandomReal(0.,100.) <= pack[k].chance then id = FourCC(pack[k].id) end end
                newunit = CreateUnit(MONSTER_PLAYER, id, GetRandomReal(GetRectMinX(rect), GetRectMaxX(rect)), GetRandomReal(GetRectMinY(rect), GetRectMaxY(rect)), GetRandomInt(0, 359))
                GroupAddUnit(WaveGroup, newunit)
            end

        return amount
    end





    local function GetProperAttackTypeSwitch(current_type, pack_attack_type)
        local monster_attack_type = current_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE

        if pack_attack_type == nil then
            monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE
        end

        return monster_attack_type
    end



    ---@param point rect
    ---@param monster_pack number
    ---@param min number
    ---@param max number
    ---@param bonus_elite number
    ---@param range_type_chance_delta number
    function SpawnMonsterPack(point, monster_pack, min, max, bonus_elite, range_type_chance_delta)
        if point == nil or monster_pack == nil then return end
        local total_monster_count = GetRandomInt(min, max)
        local first_pack_count = math.floor(total_monster_count * COMMON_MONSTER_RATE)
        local monster_attack_type = GetRandomReal(0., 100.) <= (MELEE_MONSTER_CHANCE + (range_type_chance_delta or 0.)) and MONSTER_TAG_MELEE or MONSTER_TAG_RANGE
        local monster_group = CreateGroup()

        monster_pack = MONSTER_LIST[monster_pack]

        if monster_pack[MONSTER_RANK_COMMON] == nil then
            monster_pack = GetRandomMonsterPack(MONSTER_RANK_COMMON)
        end
        --print("spawn init")

        if monster_pack[MONSTER_RANK_COMMON][monster_attack_type] == nil then
            monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE
        end

        total_monster_count = total_monster_count - CreateUnits_Pack(monster_pack[MONSTER_RANK_COMMON][monster_attack_type] or nil, point, first_pack_count, monster_group)
        --print("spawn first")
        local second_pack_count = GetRandomInt(1, total_monster_count)

        --monster_attack_type = GetProperAttackTypeSwitch(monster_attack_type, monster_pack[MONSTER_RANK_COMMON][monster_attack_type])

        monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE

        if monster_pack[MONSTER_RANK_COMMON][monster_attack_type] == nil then
            monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE
        end

        --print("spawn secind")
        total_monster_count = total_monster_count - CreateUnits_Pack(monster_pack[MONSTER_RANK_COMMON][monster_attack_type] or nil, point, second_pack_count, monster_group)

            if total_monster_count + (bonus_elite or 0) > 0 then
                --print("spawn elite - yes")
                local elite_monster_count = GetRandomInt(1, total_monster_count + (bonus_elite or 0))
                monster_attack_type = GetRandomReal(0., 100.) <= (MELEE_MONSTER_CHANCE + range_type_chance_delta) and MONSTER_TAG_MELEE or MONSTER_TAG_RANGE

                if monster_pack[MONSTER_RANK_ADVANCED] == nil then
                    monster_pack = GetRandomMonsterPack(MONSTER_RANK_ADVANCED)
                end

                if monster_pack[MONSTER_RANK_ADVANCED][monster_attack_type] == nil then
                    monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE
                end

                total_monster_count = total_monster_count - CreateUnits_Pack(monster_pack[MONSTER_RANK_ADVANCED][monster_attack_type] or nil, point, elite_monster_count, monster_group)

                if  total_monster_count > 0 then
                    monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE

                        if monster_pack[MONSTER_RANK_ADVANCED][monster_attack_type] == nil then
                            monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE
                        end

                    local elite_second_monster_count = GetRandomInt(1, total_monster_count)
                    CreateUnits_Pack(monster_pack[MONSTER_RANK_ADVANCED][monster_attack_type] or nil, point, elite_second_monster_count, monster_group)
                end

            end

        DelayAction(0.015, function()
            ScaleMonsterGroup(monster_group)
        end)

        return monster_group
    end



    ---@param point rect
    function SpawnMonstersWave(point)
        local monster_pack = GetRandomMonsterPack(MONSTER_RANK_COMMON)
        --local point = SPAWN_POINTS[1]
        local total_monster_count = GetRandomInt(WAVE_MINIMUM_COUNT, WAVE_MAXIMUM_COUNT)
        --print("total is "..total_monster_count)
        local first_pack_count = math.floor(total_monster_count * COMMON_MONSTER_RATE)
        --print("first pack counter is "..first_pack_count)
        local monster_attack_type = GetRandomReal(0., 100.) <= MELEE_MONSTER_CHANCE and MONSTER_TAG_MELEE or MONSTER_TAG_RANGE


        --print("monster attack type is "..(monster_attack_type == MONSTER_TAG_MELEE and "melee" or "range"))
        --print("pack is "..monster_pack)


        total_monster_count = total_monster_count - CreateUnits(monster_pack[MONSTER_RANK_COMMON][monster_attack_type] or nil, point, first_pack_count)
        --print("there are " .. total_monster_count .. " free slots")


        local second_pack_count = GetRandomInt(1, total_monster_count)
        monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE

        total_monster_count = total_monster_count - CreateUnits(monster_pack[MONSTER_RANK_COMMON][monster_attack_type] or nil, point, second_pack_count)
        --print("second pack counter is "..second_pack_count)
        --print("monster attack type is "..(monster_attack_type == MONSTER_TAG_MELEE and "melee" or "range"))
        --print("there are " .. total_monster_count .. " free slots")

        if total_monster_count > 0 then
            local elite_monster_count = GetRandomInt(1, total_monster_count)
            monster_attack_type = GetRandomReal(0., 100.) <= MELEE_MONSTER_CHANCE and MONSTER_TAG_MELEE or MONSTER_TAG_RANGE

                if monster_pack[MONSTER_RANK_ADVANCED][monster_attack_type] == nil then
                    monster_pack = GetRandomMonsterPackTag(MONSTER_RANK_ADVANCED, monster_attack_type)
                end

            total_monster_count = total_monster_count - CreateUnits(monster_pack[MONSTER_RANK_ADVANCED][monster_attack_type] or nil, point, elite_monster_count)
            --print("elite pack counter is "..elite_monster_count)
            --print("monster attack type is "..(monster_attack_type == MONSTER_TAG_MELEE and "melee" or "range"))
            --print("there is " .. total_monster_count .. " free slots")

            if  total_monster_count > 0 then
                monster_attack_type = monster_attack_type == MONSTER_TAG_MELEE and MONSTER_TAG_RANGE or MONSTER_TAG_MELEE

                if monster_pack[MONSTER_RANK_ADVANCED][monster_attack_type] == nil then
                    monster_pack = GetRandomMonsterPackTag(MONSTER_RANK_ADVANCED, monster_attack_type)
                end

                local elite_second_monster_count = GetRandomInt(1, total_monster_count)
                CreateUnits(monster_pack[MONSTER_RANK_ADVANCED][monster_attack_type] or nil, point, elite_second_monster_count)
                --print("alternate elite pack counter is "..elite_second_monster_count)
                --print("monster attack type is "..(monster_attack_type == MONSTER_TAG_MELEE and "melee" or "range"))
                --print("there are " .. total_monster_count .. " free slots")
            end

        end


            DelayAction(0.015, function()
                ForGroup(WaveGroup, function ()
                    ScaleMonsterUnit(GetEnumUnit())
                    IssuePointOrderById(GetEnumUnit(), order_attack, GetRectCenterX(MAIN_POINT), GetRectCenterY(MAIN_POINT))
                end)
            end)

        PingMinimap(GetRectCenterX(point), GetRectCenterY(point), 7.)

    end


    function GetRandomMonsterSpawnPoint()
        return SPAWN_POINTS[GetRandomInt(1, #SPAWN_POINTS)]
    end


    function InitMonsterData()

        SPAWN_POINTS = {
            gg_rct_spawn_left,
            gg_rct_spawn_down,
            gg_rct_spawn_right,
            gg_rct_spawn_wave_top_righ
        }

        MAIN_POINT = gg_rct_captain_guard_rect

        InitMonsterPacks()

         local trg = CreateTrigger()
            TriggerRegisterPlayerUnitEvent(trg, MONSTER_PLAYER, EVENT_PLAYER_UNIT_DEATH, nil)
            TriggerRegisterPlayerUnitEvent(trg, SECOND_MONSTER_PLAYER, EVENT_PLAYER_UNIT_DEATH, nil)
            TriggerAddAction(trg, function()

                --print("killer is " .. GetUnitName(GetKillingUnit()))

                if GetKillingUnit() ~= nil then
                    local unit = GetTriggerUnit()
                    local unit_Data = GetUnitData(unit)

                    if IsUnitInGroup(unit, WaveGroup) then
                        GroupRemoveUnit(WaveGroup, unit)
                        if BlzGroupGetSize(WaveGroup) <= 0 then EndWave() end
                    end

                    --print("pre drop")
                    DropForPlayer(unit, GetPlayerId(GetOwningPlayer(GetKillingUnit())))
                    GiveExpForKill(((unit_Data.xp or 15) + MONSTER_EXP_RATES.const_per_level) * MONSTER_EXP_RATES[unit_Data.classification or MONSTER_RANK_COMMON] * (1. + (MONSTER_EXP_RATES.modf_per_level * Current_Wave)) , GetUnitX(unit), GetUnitY(unit))

                    unit = nil
                    unit_Data = nil
                end

        end)

    end

end

