---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 15.01.2020 23:28
---
do

    MAIN_MULTIBOARD = nil
    local WaveTimer
    Current_Wave = 1


    local function TimeToText(time)
        local mins = math.floor(time / 60.)
        local secs = time - (mins * 60.)

        return R2I(mins) .. ":" .. R2I(secs)
    end



    local trigger = CreateTrigger()
    TriggerRegisterPlayerChatEvent(trigger, Player(0), "run", false)
    TriggerAddAction(trigger, function() AddWaveTimer(3.) end)



    function AddWaveTimer(total_time)
        local item = MultiboardGetItem(MAIN_MULTIBOARD, 1, 1)

            MultiboardSetItemStyle(item, true, false)
            MultiboardSetItemValue(item, TimeToText(total_time))
            TimerStart(WaveTimer, 0., false, nil)

            TimerStart(WaveTimer, 1., true, function()
                total_time = total_time - 1.
                MultiboardSetItemValue(item, TimeToText(total_time))

                    if total_time <= 0. then
                        PauseTimer(WaveTimer)
                        SpawnMonsters()
                    end

            end)

    end


    function WavesInit()

        WaveTimer = CreateTimer()
        MAIN_MULTIBOARD = CreateMultiboard()
        MultiboardSetTitleText(MAIN_MULTIBOARD, LOCALE_LIST[my_locale].WAVE_INCOMING_TEXT)
        MultiboardSetItemsStyle(MAIN_MULTIBOARD, true, false)
        MultiboardSetItemsWidth(MAIN_MULTIBOARD, 6.5 / 200.0)
        MultiboardSetColumnCount(MAIN_MULTIBOARD, 4)
        MultiboardSetRowCount(MAIN_MULTIBOARD, 4)
        MultiboardDisplay(MAIN_MULTIBOARD, true)


    end

end