---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hatsu.
--- DateTime: 26.01.2024 18:14
---
do

    function CreateMyImage(path, x, y, radius, r, g, b,start_alpha, blendmode)
        local r2 = radius * 2
        local imagepack = { image = CreateImage(path, r2, r2, r2, x - radius, y - radius, GetZ(x, y), 0, 0, 0, blendmode), r = r, g = g, b = b, a = start_alpha }

            SetImageColor(imagepack.image, r, g, b, start_alpha)
            SetImageRenderAlways(imagepack.image, true)
            ShowImage(imagepack.image, true)

        return imagepack
    end

    function FadeInImage(imagepack, time)
        local timer = CreateTimer()
        local alpha = 0
        local step = math.floor((255 / time / 40) + 0.5)

            TimerStart(timer, 0.025, true, function()
                alpha = alpha + step
                if alpha > 255 then alpha = 255; DestroyTimer(timer) end
                SetImageColor(imagepack.image, imagepack.r, imagepack.g, imagepack.b, alpha)
                imagepack.a = alpha
            end)

    end


    function FadeOutImage(imagepack, time)
        local timer = CreateTimer()
        local alpha = 255
        local step = math.floor((255 / time / 40) + 0.5)

            TimerStart(timer, 0.025, true, function()
                alpha = alpha - step
                if alpha <= 0 then alpha = 0; DestroyTimer(timer) end
                SetImageColor(imagepack.image, imagepack.r, imagepack.g, imagepack.b, alpha)
                imagepack.a = alpha
            end)

    end

    function DecolourImage(imagepack, time)
        local timer = CreateTimer()
        --local colour = 255
        --local step = math.floor((255 / time / 40) + 0.5)
        local r_step = math.floor((imagepack.r / time / 40) + 0.5)
        local g_step = math.floor((imagepack.g / time / 40) + 0.5)
        local b_step = math.floor((imagepack.b / time / 40) + 0.5)

            TimerStart(timer, 0.025, true, function()
                imagepack.r = imagepack.r - r_step
                imagepack.g = imagepack.g - g_step
                imagepack.b = imagepack.b - b_step
                if imagepack.r < 0 then imagepack.r = 0 end
                if imagepack.g < 0 then imagepack.g = 0 end
                if imagepack.b < 0 then imagepack.b = 0 end
                SetImageColor(imagepack.image, imagepack.r, imagepack.g,  imagepack.b, imagepack.a)
                time = time - 0.025
                if time <= 0 then DestroyTimer(timer) end
            end)

    end

    function ColourImage(imagepack, target_r, target_g, target_b, time)
        local timer = CreateTimer()
        local colour = 0
        local step = math.floor((255 / time / 40) + 0.5)
        local r_step = math.floor((target_r / time / 40) + 0.5)
        local g_step = math.floor((target_g / time / 40) + 0.5)
        local b_step = math.floor((target_b / time / 40) + 0.5)

            TimerStart(timer, 0.025, true, function()
                colour = colour + step
                imagepack.r = imagepack.r + r_step
                imagepack.g = imagepack.g + g_step
                imagepack.b = imagepack.b + b_step
                if imagepack.g > target_g then imagepack.g = target_g end
                if imagepack.r > target_r then imagepack.r = target_r end
                if imagepack.b > target_b then imagepack.b = target_b end
                if colour >= 255 then colour = 255; DestroyTimer(timer) end
                SetImageColor(imagepack.image, imagepack.r, imagepack.g, imagepack.b, imagepack.a)
                time = time - 0.025
                if time <= 0 then DestroyTimer(timer) end
            end)

    end

end