---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 05.07.2021 15:00
---
do


    PlayerMousePosition = 0
    PlayerMouseFocus = 0
    PlayerMouseVectorAngle = nil
    local mouse_track_trigger = 0


    function MouseTrackingInit()

        PlayerMousePosition = {}
        PlayerMouseFocus = {}
        PlayerMouseVectorAngle = {}
        mouse_track_trigger = CreateTrigger()

        for i = 0, 5 do
            TriggerRegisterPlayerEvent(mouse_track_trigger, Player(i), EVENT_PLAYER_MOUSE_MOVE)
            PlayerMousePosition[i+1] = {}
        end

        TriggerAddAction(mouse_track_trigger, function()
            if BlzGetTriggerPlayerMouseX() ~= 0. then
                local player = GetPlayerId(GetTriggerPlayer()) + 1
                local mouse_focus = BlzGetMouseFocusUnit()

                    PlayerMousePosition[player].x = BlzGetTriggerPlayerMouseX()
                    PlayerMousePosition[player].y = BlzGetTriggerPlayerMouseY()
                    PlayerMouseVectorAngle[player] = math.deg(AngleBetweenXY(GetUnitX(PlayerHero[player]), GetUnitY(PlayerHero[player]), PlayerMousePosition[player].x, PlayerMousePosition[player].y))

                    if mouse_focus ~= nil and GetUnitState(mouse_focus, UNIT_STATE_LIFE) > 0.045 and GetUnitAbilityLevel(mouse_focus, FourCC("Avul")) == 0 then
                        PlayerMouseFocus[player] = mouse_focus
                    else
                        PlayerMouseFocus[player] = nil
                    end

            end
        end)


    end


end