---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 22.03.2022 3:25
---
do

    local AuraTemplate = nil
    AuraList = nil


    function GetAuraData(id)
        return AuraTemplate[id] or nil
    end


    function NewAuraTemplate(aura)
        AuraTemplate[aura.id] = aura

        if aura.max_level > 1 then
            for i = 2, aura.max_level do
                if not aura.level[i] then
                    aura.level[i] = MergeTables({}, aura.level[1])
                end
            end
        end

    end


    function InitAuras()

        AuraTemplate = {}
        AuraList = {}


        NewAuraTemplate({
            id = "grave_cold_aura",
            name = "grave cold aura",
            max_level = 1,
            sfx_path = "Effect\\RemorselessWinter.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 340.,
                    duration = 5.,
                    [ON_ENEMY] = { applied_effect = "effect_grave_cold" }
                }
            }
        })

        NewAuraTemplate({
            id = "hydra_aura",
            name = "hydra fire aura",
            max_level = 75,
            sfx_path = "",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 650.,
                    [ON_SELF] = { applied_buff = "HDAU" },
                    [ON_ALLY] = { applied_buff = "HDAU" }
                }
            }
        })

        NewAuraTemplate({
            id = "lich_aura",
            name = "lich aura",
            max_level = 75,
            sfx_path = "Abilities\\Spells\\Human\\Brilliance\\Brilliance.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 750.,
                    [ON_ALLY] = { applied_buff = "NRLA" }
                }
            }
        })

        NewAuraTemplate({
            id = "caltrops_aura",
            name = "caltrops aura",
            max_level = 1,
            sfx_path = "Abilities\\Spells\\Undead\\UnholyAura\\UnholyAura.mdx",
            tickrate = 0.2,
            level = {
                [1] = {
                    sfx_scale = 1.5,
                    radius = 350.,
                    duration = 5.,
                    [ON_ENEMY] = { applied_effect = "caltrops_effect" }
                }
            }
        })

        NewAuraTemplate({
            id = "twilight_aura",
            name = "twilight aura",
            max_level = 75,
            sfx_path = "Effect\\Black Mist.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.5,
                    radius = 450.,
                    duration = 6.,
                    [ON_ENEMY] = { applied_effect = "twilight_effect" },
                    [ON_SELF] = { applied_buff = "ABTH" }
                }
            }
        })

        NewAuraTemplate({
            id = "monster_physical_aura",
            name = "monster physical aura",
            max_level = 1,
            sfx_path = "Effect\\Providence Aura.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 700.,
                    [ON_ALLY] = { applied_buff = "MPHA" }
                }
            }
        })

        NewAuraTemplate({
            id = "monster_primal_aura",
            name = "monster primal aura",
            max_level = 1,
            sfx_path = "Effect\\Providence Aura Red.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 700.,
                    [ON_ALLY] = { applied_buff = "MPRA" }
                }
            }
        })

        NewAuraTemplate({
            id = "monster_shadow_aura",
            name = "monster shadow aura",
            max_level = 1,
            sfx_path = "Effect\\Providence Aura Purple.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 700.,
                    [ON_ALLY] = { applied_buff = "MSHA" }
                }
            }
        })

        NewAuraTemplate({
            id = "monster_universal_aura",
            name = "monster universal aura",
            max_level = 1,
            sfx_path = "Effect\\Providence Aura Green.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 700.,
                    [ON_ALLY] = { applied_buff = "MUNA" }
                }
            }
        })

        NewAuraTemplate({
            id = "monster_sturdy_aura",
            name = "monster str aura",
            max_level = 1,
            sfx_path = "Effect\\Providence Aura Teal.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 700.,
                    [ON_ALLY] = { applied_buff = "MSTA" }
                }
            }
        })



    end

end