---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 22.03.2022 3:25
---
do

    AuraTemplate = nil
    AuraList = nil


    function GetAuraData(id)
        return AuraTemplate[id] or nil
    end


    function NewAuraTemplate(aura)
        AuraTemplate[aura.id] = aura

        if aura.max_level > 1 then
            for i = 2, aura.max_level do
                aura.level[i] = MergeTables({}, aura.level[1])
            end
        end

    end


    function InitAuras()

        AuraTemplate = {}
        AuraList = {}


        NewAuraTemplate({
            id = "grave_cold_aura",
            name = "grave cold aura",
            max_level = 1,
            sfx_path = "Effect\\RemorselessWinter.mdx",
            sfx_point = "origin",
            tickrate = 0.5,
            level = {
                [1] = {
                    sfx_scale = 1.,
                    radius = 340.,
                    duration = 5.,
                    [ON_ENEMY] = {
                        applied_effect = "effect_grave_cold"
                    }
                }
            }
        })


        RegisterTestCommand("aon", function()
            ToggleAuraOnUnit(PlayerHero[1], "grave_cold_aura", 1, true)
        end)

        RegisterTestCommand("aoff", function()
            ToggleAuraOnUnit(PlayerHero[1], "grave_cold_aura", 1, false)
        end)

    end

end