---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 12.10.2021 3:04
---
do

    local Conversations
    local CONSTANT_TEXT_SIZE =  (9. * 0.023) / 10



    function GetConversation(id)
        return Conversations[id]
    end


    function NewConversation(id, pack)
        Conversations[id] = pack
    end


    ---@param id string
    ---@param npc unit
    ---@param player integer
    function PlayConversation(id, npc, player)
        local texttag = CreateTextTag()
        local conv = GetConversation(id)
        local duration = conv[1].duration
        local a = GetLocalPlayer() == Player(player-1) and 255 or 0
        local index = 1
        local unit_data = GetUnitData(npc)

            unit_data.interaction_blocked[player] = true

            if Conversations[player].texttag then
                unit_data = GetUnitData(Conversations[player].npc)
                unit_data.interaction_blocked[player] = nil
                DestroyTextTag(Conversations[player].texttag)
            end

            Conversations[player].texttag = texttag
            Conversations[player].npc = npc

            SetTextTagText(texttag, "[1/" .. #conv .. "] " .. conv[1].phrase, CONSTANT_TEXT_SIZE)
            SetTextTagPos(texttag, GetUnitX(npc), GetUnitY(npc), 45. + GetUnitFlyHeight(npc))
            SetTextTagColor(texttag, 255, 255, 255, a)


            TimerStart(Conversations[player].timer, 0.05, true, function()

                if duration <= 0. then
                    index = index + 1

                        if not IsUnitInRange(PlayerHero[player], npc, 500.) or not conv[index] then
                            DestroyTextTag(texttag)
                            unit_data.interaction_blocked[player] = nil
                            Conversations[player].texttag = nil
                            if conv[index].feedback then
                                conv[index].feedback(id, npc, player)
                            end
                        else
                            duration = conv[index].duration
                            SetTextTagText(texttag, "[".. index .. "/" .. #conv .. "] " .. conv[index].phrase, CONSTANT_TEXT_SIZE)
                        end

                else
                    if not IsUnitInRange(PlayerHero[player], npc, 500.) then duration = 0.
                    else duration  = duration - 0.05 end
                end

            end)


    end


    function InitConversations()

        Conversations = {
            last_conversation = {}
        }

        for i = 1, 6 do
            --Conversations.last_conversation[i]
            Conversations[i] = {}
            Conversations[i].timer = CreateTimer()
        end

        NewConversation("peon", {
            { phrase = "Я каменщик", duration = 1.68 },
            { phrase = "Работал три дня!", duration = 1.76 },
            { phrase = "Без еды без зарплаты!", duration = 2. },
            { phrase = "ууууууууууу", duration = 1.9 },
        })

        NewConversation("bill_intro", {
            { phrase = LOCALE_LIST[my_locale].BILL_CONV_INTRO_1, duration = 1.68 },
            { phrase = LOCALE_LIST[my_locale].BILL_CONV_INTRO_2, duration = 2.35 },
            { phrase = LOCALE_LIST[my_locale].BILL_CONV_INTRO_3, duration = 1.75 },
            { phrase = LOCALE_LIST[my_locale].BILL_CONV_INTRO_4, duration = 1.65 },
        })

        NewConversation("dalia_intro", {
            { phrase = LOCALE_LIST[my_locale].DALIA_CONV_INTRO_1, duration = 1.55 },
            { phrase = LOCALE_LIST[my_locale].DALIA_CONV_INTRO_2, duration = 3.15 },
        })

        NewConversation("blacksmith_intro", {
            { phrase = LOCALE_LIST[my_locale].BLACKSMITH_CONV_INTRO_1, duration = 1.75 },
            { phrase = LOCALE_LIST[my_locale].BLACKSMITH_CONV_INTRO_2, duration = 2.45 },
            { phrase = LOCALE_LIST[my_locale].BLACKSMITH_CONV_INTRO_3, duration = 2.55 },
        })

        NewConversation("librarian_intro", {
            { phrase = LOCALE_LIST[my_locale].LIBRARIAN_CONV_INTRO_1, duration = 3.75 },
            { phrase = LOCALE_LIST[my_locale].LIBRARIAN_CONV_INTRO_2, duration = 2.45 },
        })

        NewConversation("smorc_intro", {
            { phrase = LOCALE_LIST[my_locale].SMORC_CONV_INTRO_1, duration = 2.85 },
            { phrase = LOCALE_LIST[my_locale].SMORC_CONV_INTRO_2, duration = 3.45 },
            { phrase = LOCALE_LIST[my_locale].SMORC_CONV_INTRO_3, duration = 3.45 },
        })

        NewConversation("lynn_intro", {
            { phrase = LOCALE_LIST[my_locale].LYNN_CONV_INTRO_1, duration = 2.85 },
            { phrase = LOCALE_LIST[my_locale].LYNN_CONV_INTRO_2, duration = 2.85 },
            { phrase = LOCALE_LIST[my_locale].LYNN_CONV_INTRO_3, duration = 4.45 },
        })

        NewConversation("wandering_intro", {
            { phrase = LOCALE_LIST[my_locale].WANDERING_CONV_INTRO_1, duration = 4.55 },
            { phrase = LOCALE_LIST[my_locale].WANDERING_CONV_INTRO_2, duration = 3.85 },
            { phrase = LOCALE_LIST[my_locale].WANDERING_CONV_INTRO_3, duration = 2.75 },
        })

    end

end