---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 07.10.2021 19:35
---
do

    local Droplists
    local GOLD_CONST_PER_LEVEL = 1
    local GOLD_MOD_PER_LEVEL = 0.011

    ---@param id string
    function GetDropList(id)
        return Droplists[id] or nil
    end


    ---@param id string
    ---@param list table
    function NewDropList(id, list)
        Droplists[id] = list
    end


    ---@param unit unit
    ---@param droplist string
    ---@param chance real
    ---@param position integer
    function AddDropList(unit, droplist, chance, position)
        local unit_data = GetUnitData(unit)
        local new_droplist = { id = droplist, chance = chance }

            position = position and position or #unit_data.droplist.list-1
            table.insert(unit_data.droplist.list, position, MergeTables({}, new_droplist))

    end


    ---@param unit unit
    ---@param droplist string
    function SetDropList(unit, droplist)
        local unit_data = GetUnitData(unit)

        if not unit_data then
            UnitsList[GetHandleId(unit)] = {}
            unit_data = UnitsList[GetHandleId(unit)]
        end

        unit_data.droplist = MergeTables({}, GetDropList(droplist))
    end


    ---@param unit unit
    ---@param droplist string
    ---@return integer
    function RemoveDropList(unit, droplist)
        local unit_data = GetUnitData(unit)

            for i = 1, #unit_data.droplist.list do
                if unit_data.droplist.list[i].id == droplist then
                    table.remove(unit_data.droplist.list, i)
                    return i
                end
            end

    end

    ---@param unit unit
    ---@param droplist string
    ---@param chance real
    function SetDropChance(unit, droplist, chance)
         local unit_data = GetUnitData(unit)

            for i = 1, #unit_data.droplist.list do
                if unit_data.droplist.list[i].id == droplist then
                    unit_data.droplist.list[i].chance = chance
                    break
                end
            end
    end

    ---@param id string
    local function GetProperDropList(id)
        local droplist = GetDropList(id)

            if droplist.template then
                for i = 1, #droplist.list do
                    if Chance(droplist.list[i].chance or 100.) then
                        return GetProperDropList(droplist.list[i].id)
                    end
                end
            else
                return droplist
            end


    end

    ---@param droplist table
    ---@param bundle table
    ---@param min integer
    ---@param max integer
    local function AddItemsToDropBundle(droplist, bundle, bonus_drop_chance, global_min)
        local list = droplist.list
        local min = droplist.min or 0
        local max = droplist.max or 1
        local rolls = droplist.rolls or 1
        local random
        local current_item_count = 0

            for roll = 1, rolls do
                random = GetRandomIntTable(1, #list, #list)
                for i = 1, #list do
                    local chance = current_item_count < min and 126. or (list[random[i]].chance or 100.)

                    if global_min > 0 and chance < 100. then
                        chance = 100.
                        global_min = global_min - 1
                    end

                    if Chance(chance * bonus_drop_chance) then

                        if list[random[i]].generate then
                            list[random[i]].quality_list = droplist.quality
                        end

                        bundle[#bundle + 1] = list[random[i]]
                    end

                    current_item_count = current_item_count + 1
                    if current_item_count >= max then break end
                end
            end

    end


    ---@param player number
    ---@param x real
    ---@param y real
    ---@param min_offset real
    ---@param max_offset real
    ---@param droplist table
    function DropDroplistForPlayer(player, x, y, min_offset, max_offset, droplist)
        local item_drop = {}
        local min = droplist.min or 0
        local max = droplist.max or 1
        local current = 0
        local initial_time_offset = 0.45
        local time_offset = 0.
        local bonus_drop_chance = 1. + GetUnitParameterValue(PlayerHero[player], DROP_BONUS) * 0.01


            for i = 1, #droplist.list do
                if Chance(droplist.list[i].chance * bonus_drop_chance * GLOBAL_DROP_RATE) then
                    local inner_droplist = GetProperDropList(droplist.list[i].id)

                        if inner_droplist then
                            AddItemsToDropBundle(inner_droplist, item_drop, bonus_drop_chance * GLOBAL_DROP_RATE, min)
                        end

                end
            end

            --print("to drop "..#item_drop)
            if #item_drop > 0 then
                for i = 1, #item_drop do
                    if current < max or item_drop[i].ignore_max then

                        DelayAction(initial_time_offset + time_offset, function()
                            local angle = GetRandomReal(0., 359.)
                            local drop_offset = GetMaxAvailableDistance(x, y, angle, GetRandomReal(min_offset or 45., max_offset or 65.))
                            local new_x = x + Rx(drop_offset, angle)
                            local new_y = y + Ry(drop_offset, angle)


                                if item_drop[i].id == "gold" then
                                    CreateGoldStack(math.floor((GetRandomInt(item_drop[i].min, item_drop[i].max) + (GOLD_CONST_PER_LEVEL * Current_Wave)) * (1. + GOLD_MOD_PER_LEVEL * Current_Wave) * (1. + GetUnitParameterValue(PlayerHero[player], GOLD_BONUS) * 0.01) * GLOBAL_GOLD_RATE), new_x, new_y, player-1)
                                else
                                    local id = item_drop[i].id

                                        if id == "common_books_restricted" or id == "rare_books_restricted" or id == "magic_books_restricted" then

                                            if Chance(65.) then
                                                local class = GetUnitClass(PlayerHero[player])

                                                    if id == "common_books_restricted" then id = GetRandomBookClass(class, COMMON_ITEM)
                                                    elseif id == "rare_books_restricted" then id = GetRandomBookClass(class, RARE_ITEM)
                                                    else id = GetRandomBookClass(class, MAGIC_ITEM) end

                                            else
                                                if id == "common_books_restricted" then id = GetRandomBookItemId(COMMON_ITEM)
                                                elseif id == "rare_books_restricted" then id = GetRandomBookItemId(RARE_ITEM)
                                                else id = GetRandomBookItemId(MAGIC_ITEM) end
                                            end

                                        end
                                    
                                    local item = CreateCustomItem(id, new_x, new_y, true, player-1)

                                        if item_drop[i].generate then
                                            local item_data = GetItemData(item)

                                            if item_data.QUALITY == SET_ITEM or item_data.QUALITY == UNIQUE_ITEM then
                                                GenerateItemLevel(item, Current_Wave + GetRandomInt(0, 2))
                                            else
                                                local quality = COMMON_ITEM

                                                for k = 1, #item_drop[i].quality_list do
                                                    if Chance(item_drop[i].quality_list[k].chance) then
                                                        quality = item_drop[i].quality_list[k].quality
                                                        break
                                                    end
                                                end

                                                GenerateItemStats(item, Current_Wave + GetRandomInt(0, 2), quality)
                                            end

                                        elseif GetItemType(item) == ITEM_TYPE_CHARGED then
                                            SetItemCharges(item, GetRandomInt(item_drop[i].min or 1, item_drop[i].max or 1))
                                        end

                                    DelayAction(480., function()
                                        local item_data = GetItemData(item)
                                        if item and item_data and item_data.item and item_data.owner then
                                            RemoveCustomItem(item)
                                        end
                                end)

                                end

                            --print(item_drop[i].id)
                        end)

                        time_offset = time_offset + 0.347
                        current = current + 1
                    end

                end
            end

            --print("done")
    end


    ---@param dying_unit unit
    ---@param player integer
    function DropForPlayer(dying_unit, player)
        local x = GetUnitX(dying_unit)
        local y = GetUnitY(dying_unit)
        local unit_data = GetUnitData(dying_unit)

            DropDroplistForPlayer(player+1, x, y, unit_data.drop_offset_min or nil, unit_data.drop_offset_max or nil, unit_data.droplist)


    end

    function InitDroplist()
        Droplists = {}

        NewDropList("common_item", {
            quality = {
                { quality = MAGIC_ITEM, chance = 5. },
                { quality = RARE_ITEM, chance = 25. },
                { quality = COMMON_ITEM, chance = 100. },
            },
            list = {
                { id = GetGeneratedItemId(SWORD_WEAPON), generate = true  },
                { id = GetGeneratedItemId(GREATSWORD_WEAPON), generate = true },
                { id = GetGeneratedItemId(AXE_WEAPON), generate = true },
                { id = GetGeneratedItemId(GREATAXE_WEAPON), generate = true },
                { id = GetGeneratedItemId(BLUNT_WEAPON), generate = true },
                { id = GetGeneratedItemId(GREATBLUNT_WEAPON), generate = true },
                { id = GetGeneratedItemId(STAFF_WEAPON), generate = true },
                { id = GetGeneratedItemId(DAGGER_WEAPON), generate = true },
                { id = GetGeneratedItemId(BOW_WEAPON), generate = true },
                { id = GetGeneratedItemId(CHEST_ARMOR), generate = true },
                { id = GetGeneratedItemId(HEAD_ARMOR), generate = true },
                { id = GetGeneratedItemId(HANDS_ARMOR), generate = true },
                { id = GetGeneratedItemId(LEGS_ARMOR), generate = true },
                { id = GetGeneratedItemId(NECKLACE_JEWELRY), generate = true },
                { id = GetGeneratedItemId(RING_JEWELRY), generate = true },
                { id = GetGeneratedItemId(SHIELD_OFFHAND), generate = true },
                { id = GetGeneratedItemId(ORB_OFFHAND), generate = true },
                { id = GetGeneratedItemId(BELT_ARMOR), generate = true },
                { id = GetGeneratedItemId(QUIVER_OFFHAND), generate = true },
            }
        })

        NewDropList("set_items", {
            list = {
                { id = "I01B", generate = true }, --queen
                { id = "I01A", generate = true }, --princess
                { id = "I01E", generate = true }, --bootpain
                { id = "I01F", generate = true }, --chestpain
                { id = "I01G", generate = true }, --headpain
                { id = "I01H", generate = true }, --king
                { id = "I01I", generate = true }, --jester
                { id = "I02J", generate = true }, --crimson
                { id = "I02K", generate = true }, --crimson
                { id = "I02L", generate = true }, --crimson
                { id = "I02I", generate = true }, --crimson
            }
        })

        NewDropList("unique_items", {
            list = {
                { id = "I00O", generate = true }, --COWARD
                { id = "I00P", generate = true }, --witch
                { id = "I00Q", generate = true }, --crown
                { id = "I00R", generate = true }, --ritual
                { id = "I00S", generate = true }, --acolyte
                { id = "I00T", generate = true }, --smorc
                { id = "I018", generate = true }, --boosters
                { id = "I019", generate = true }, --storm
                { id = "I01A", generate = true }, --princess
                { id = "I01B", generate = true }, --queen
                { id = "I01C", generate = true }, --pain
                { id = "I01D", generate = true }, --axe
                { id = "I01E", generate = true }, --bootpain
                { id = "I01F", generate = true }, --chestpain
                { id = "I01G", generate = true }, --headpain
                { id = "I01H", generate = true }, --king
                { id = "I01I", generate = true }, --jester
                { id = "I02J", generate = true }, --crimson
                { id = "I02K", generate = true }, --crimson
                { id = "I02L", generate = true }, --crimson
                { id = "I02I", generate = true }, --crimson
                { id = "I01J", generate = true }, --master
                { id = "I01W", generate = true }, --ice touch
                { id = "I02E", generate = true }, --blood drinker
                { id = "I02G", generate = true }, --primal tome
                { id = "I02Q", generate = true }, --mask of shadows
                { id = "I02R", generate = true }, --splitter
                { id = "I02S", generate = true }, --executioner
                { id = "I02X", generate = true }, --fullmoon
                { id = "I037", generate = true }, --pain conductor
                { id = "I03A", generate = true }, --catalyst
                { id = "I03T", generate = true }, --greta
                { id = "I03U", generate = true }, --unity
                { id = "I03Y", generate = true }, --death cry
                { id = "I03Z", generate = true }, --rot
                { id = "I040", generate = true }, --horrors
                { id = "I041", generate = true }, --madness
                { id = "I042", generate = true }, --skinripper
                { id = "I043", generate = true }, --grounder
                { id = "I00N", generate = true }, --rat hunter
                { id = "I047", generate = true }, --infinity chain
                { id = "I04M", generate = true }, --nightwalkers
                { id = "I04N", generate = true }, --trick
                { id = "I04X", generate = true }, --icebound
                { id = "I04Z", generate = true }, --serpentfang
                { id = "I050", generate = true }, --crownhollow
                { id = "I051", generate = true }, --dawnweaver
                { id = "I01L", generate = true }, --nightwatch
            }
        })


        --NewDropList("unique_items_supply", MergeTables({}, GetDropList("unique_items"))

        NewDropList("gems", {
            max = 2,
            rolls = 4,
            list = {
                { id = ITEM_STONE_DIAMOND, chance = 30. },
                { id = ITEM_STONE_AMETHYST, chance = 30. },
                { id = ITEM_STONE_TURQUOISE, chance = 30. },
                { id = ITEM_STONE_EMERALD, chance = 30. },
                { id = ITEM_STONE_MALACHITE, chance = 30. },
                { id = ITEM_STONE_JADE, chance = 30. },
                { id = ITEM_STONE_OPAL, chance = 30. },
                { id = ITEM_STONE_RUBY, chance = 30. },
                { id = ITEM_STONE_SAPPHIRE, chance = 30. },
                { id = ITEM_STONE_TOPAZ, chance = 30. },
                { id = ITEM_STONE_AMBER, chance = 30. },
                { id = ITEM_STONE_AQUAMARINE, chance = 30. },
            }
        })

        NewDropList("runes", {
            max = 2,
            rolls = 3,
            list = {
                { id = ITEM_RUNE_FEH, chance = 15. },
                { id = ITEM_RUNE_GEBO, chance = 15. },
                { id = ITEM_RUNE_RAIDO, chance = 15. },
                { id = ITEM_RUNE_DAG, chance = 15. },
                { id = ITEM_RUNE_SOL, chance = 15. },
                { id = ITEM_RUNE_ISA, chance = 15. },
                { id = ITEM_RUNE_EHW, chance = 15. },
                { id = ITEM_RUNE_BER, chance = 15. },
                { id = ITEM_RUNE_KANO, chance = 15. },
            }
        })

        NewDropList("gifts", {
            max = 1,
            rolls = 3,
            list = {
                { id = "I03D", chance = 10. },
                { id = "I03O", chance = 7. },
                { id = "I03R", chance = 10. },
                { id = "I03S", chance = 10. },
                { id = "I03V", chance = 15. },
                { id = "I03W", chance = 15. },
                { id = "I03X", chance = 15. },
            }
        })

        NewDropList("gems_supply", {
            max = 4,
            rolls = 5,
            list = {
                { id = ITEM_STONE_DIAMOND, chance = 30., min = 3, max = 5 },
                { id = ITEM_STONE_AMETHYST, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_TURQUOISE, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_EMERALD, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_MALACHITE, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_JADE, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_OPAL, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_RUBY, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_SAPPHIRE, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_TOPAZ, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_AMBER, chance = 30.,  min = 3, max = 5 },
                { id = ITEM_STONE_AQUAMARINE, chance = 30.,  min = 3, max = 5 },
            }
        })

        NewDropList("runes_supply", {
            max = 2,
            rolls = 4,
            list = {
                { id = ITEM_RUNE_FEH, chance = 30., min = 2, max = 2 },
                { id = ITEM_RUNE_GEBO, chance = 30., min = 2, max = 2 },
                { id = ITEM_RUNE_RAIDO, chance = 30., min = 2, max = 2 },
                { id = ITEM_RUNE_DAG, chance = 30., min = 2, max = 2 },
                { id = ITEM_RUNE_SOL, chance = 30., min = 2, max = 2 },
                { id = ITEM_RUNE_ISA, chance = 30., min = 2, max = 2 },
                { id = ITEM_RUNE_EHW, chance = 30., min = 2, max = 2 },
                { id = ITEM_RUNE_BER, chance = 30., min = 2, max = 2 },
                { id = ITEM_RUNE_KANO, chance = 30., min = 2, max = 2 },
            }
        })

        NewDropList("consumables", {
            max = 2,
            rolls = 3,
            list = {
                { id = ITEM_POTION_HEALTH_WEAK, chance = 10.7, max = 3 },
                { id = ITEM_POTION_MANA_WEAK, chance = 10.7, max = 3 },
                { id = ITEM_POTION_HEALTH_HALF, chance = 8.3, max = 3 },
                { id = ITEM_POTION_MANA_HALF, chance = 8.3, max = 3 },
                { id = ITEM_POTION_ANTIDOTE, chance = 5.9 },
                { id = ITEM_POTION_ADRENALINE, chance = 6.5 },
                { id = ITEM_SCROLL_OF_TOWN_PORTAL, chance = 8.3 },
                { id = ITEM_SCROLL_OF_PROTECTION, chance = 7.4 },
                { id = ITEM_SCROLL_OF_PETRI, chance = 7.4 },
                { id = ITEM_NECRONOMICON, chance = 9., max = 2 },
                { id = ITEM_ELIXIR_INNOCENCE, chance = 4.7, max = 3 },
                { id = ITEM_ASHEN_TONIC, chance = 4.7, max = 3 },
            }
        })

        NewDropList("consumables_potions_strong", {
            max = 2,
            rolls = 3,
            list = {
                { id = ITEM_POTION_HEALTH_STRONG, chance = 15., max = 2 },
                { id = ITEM_POTION_MANA_STRONG, chance = 15., max = 2 },
            }
        })

        NewDropList("consumables_supply", {
            max = 3,
            rolls = 5,
            list = {
                { id = ITEM_POTION_HEALTH_WEAK, chance = 30., max = 5 },
                { id = ITEM_POTION_MANA_WEAK, chance = 30., max = 5 },
                { id = ITEM_POTION_HEALTH_HALF, chance = 30., max = 5 },
                { id = ITEM_POTION_MANA_HALF, chance = 30., max = 5 },
                { id = ITEM_POTION_ANTIDOTE, chance = 15., max = 5 },
                { id = ITEM_POTION_ADRENALINE, chance = 15., max = 5 },
                { id = ITEM_SCROLL_OF_PROTECTION, chance = 10., max = 5 },
                { id = ITEM_SCROLL_OF_PETRI, chance = 10., max = 5 },
                { id = ITEM_NECRONOMICON, chance = 25., max = 5 },
                { id = ITEM_ELIXIR_INNOCENCE, chance = 15., max = 5 },
                { id = ITEM_ASHEN_TONIC, chance = 15., max = 5 },
            }
        })

        NewDropList("special_items", {
            list = {
                { id = "I027", chance = 50. },
                { id = "I01V", chance = 50. },
            }
        })

        NewDropList("shard", {
            list = {
                { id = "I01O", min = 1, max = 2, ignore_max = true },
            }
        })

        NewDropList("shard_event", {
            list = {
                { id = "I01O", min = 1, max = 3, ignore_max = true },
            }
        })

        NewDropList("gold_common", {
            list = {
                { id = "gold", min = 11, max = 37, ignore_max = true },
            }
        })

        NewDropList("gold_adv", {
            list = {
                { id = "gold", min = 20, max = 45, ignore_max = true },
            }
        })

        NewDropList("gold_chest", {
            list = {
                { id = "gold", min = 300, max = 1500, ignore_max = true },
            }
        })

        NewDropList("gold_supply", {
            list = {
                { id = "gold", min = 75, max = 215, ignore_max = true },
            }
        })

        NewDropList("gold_boss", {
            list = {
                { id = "gold", min = 250, max = 1250, ignore_max = true },
            }
        })

        NewDropList("common_books", {
            list = {
                { id = "I017" },
                { id = "I016" },
                { id = "I015" },
                { id = "I014" },
                { id = "I013" },
                { id = "I00V" },
                { id = "I00U" },
                { id = "I028" },
                { id = "I029" },
                { id = "I02A" },
                { id = "I03E" },
                { id = "I03F" },
                { id = "I03G" },
                { id = "I044" },
                { id = "I04O" },
                { id = "I04R" },
                { id = "I04U" }
            }
        })

        NewDropList("rare_books", {
            list = {
                { id = "I023" },
                { id = "I024" },
                { id = "I025" },
                { id = "I021" },
                { id = "I020" },
                { id = "I01Z" },
                { id = "I022" },
                { id = "I02B" },
                { id = "I02C" },
                { id = "I02D" },
                { id = "I03H" },
                { id = "I03I" },
                { id = "I03J" },
                { id = "I045" },
                { id = "I04P" },
                { id = "I04S" },
                { id = "I04V" }
            }
        })

        NewDropList("magic_books", {
            list = {
                { id = "I04C" },
                { id = "I04D" },
                { id = "I04E" },
                { id = "I048" },
                { id = "I049" },
                { id = "I04A" },
                { id = "I04B" },
                { id = "I04F" },
                { id = "I04G" },
                { id = "I04H" },
                { id = "I04I" },
                { id = "I04J" },
                { id = "I04K" },
                { id = "I04L" },
                { id = "I04Q" },
                { id = "I04T" },
                { id = "I04W" }
            }
        })

        NewDropList("library_common_books_low", {
            rolls = 5,
            list = {
                { id = "I017" },
                { id = "I016" },
                { id = "I015" },
                { id = "I014" },
                { id = "I013" },
                { id = "I00V" },
                { id = "I00U" },
                { id = "I028" },
                { id = "I029" },
                { id = "I02A" },
                { id = "I03E" },
                { id = "I03F" },
                { id = "I03G" },
                { id = "I044" },
                { id = "I04O" },
                { id = "I04R" },
                { id = "I04U" }
            }
        })

        NewDropList("library_rare_books_low", {
            rolls = 4,
            list = {
                { id = "I023" },
                { id = "I024" },
                { id = "I025" },
                { id = "I021" },
                { id = "I020" },
                { id = "I01Z" },
                { id = "I022" },
                { id = "I02B" },
                { id = "I02C" },
                { id = "I02D" },
                { id = "I03H" },
                { id = "I03I" },
                { id = "I03J" },
                { id = "I045" },
                { id = "I04P" },
                { id = "I04S" },
                { id = "I04V" }
            }
        })

        NewDropList("library_magic_books_low", {
            rolls = 3,
            list = {
                { id = "I04C" },
                { id = "I04D" },
                { id = "I04E" },
                { id = "I048" },
                { id = "I049" },
                { id = "I04A" },
                { id = "I04B" },
                { id = "I04F" },
                { id = "I04G" },
                { id = "I04H" },
                { id = "I04I" },
                { id = "I04J" },
                { id = "I04K" },
                { id = "I04L" },
                { id = "I04Q" },
                { id = "I04T" },
                { id = "I04W" }
            }
        })

        NewDropList("library_common_books_mid", {
            rolls = 6,
            list = {
                { id = "I017" },
                { id = "I016" },
                { id = "I015" },
                { id = "I014" },
                { id = "I013" },
                { id = "I00V" },
                { id = "I00U" },
                { id = "I028" },
                { id = "I029" },
                { id = "I02A" },
                { id = "I03E" },
                { id = "I03F" },
                { id = "I03G" },
                { id = "I044" },
                { id = "I04O" },
                { id = "I04R" },
                { id = "I04U" }
            }
        })

        NewDropList("library_rare_books_mid", {
            rolls = 5,
            list = {
                { id = "I023" },
                { id = "I024" },
                { id = "I025" },
                { id = "I021" },
                { id = "I020" },
                { id = "I01Z" },
                { id = "I022" },
                { id = "I02B" },
                { id = "I02C" },
                { id = "I02D" },
                { id = "I03H" },
                { id = "I03I" },
                { id = "I03J" },
                { id = "I045" },
                { id = "I04P" },
                { id = "I04S" },
                { id = "I04V" }
            }
        })

        NewDropList("library_magic_books_mid", {
            rolls = 4,
            list = {
                { id = "I04C" },
                { id = "I04D" },
                { id = "I04E" },
                { id = "I048" },
                { id = "I049" },
                { id = "I04A" },
                { id = "I04B" },
                { id = "I04F" },
                { id = "I04G" },
                { id = "I04H" },
                { id = "I04I" },
                { id = "I04J" },
                { id = "I04K" },
                { id = "I04L" },
                { id = "I04Q" },
                { id = "I04T" },
                { id = "I04W" }
            }
        })

        NewDropList("library_common_books_high", {
            rolls = 7,
            list = {
                { id = "I017" },
                { id = "I016" },
                { id = "I015" },
                { id = "I014" },
                { id = "I013" },
                { id = "I00V" },
                { id = "I00U" },
                { id = "I028" },
                { id = "I029" },
                { id = "I02A" },
                { id = "I03E" },
                { id = "I03F" },
                { id = "I03G" },
                { id = "I044" },
                { id = "I04O" },
                { id = "I04R" },
                { id = "I04U" }
            }
        })

        NewDropList("library_rare_books_high", {
            rolls = 6,
            list = {
                { id = "I023" },
                { id = "I024" },
                { id = "I025" },
                { id = "I021" },
                { id = "I020" },
                { id = "I01Z" },
                { id = "I022" },
                { id = "I02B" },
                { id = "I02C" },
                { id = "I02D" },
                { id = "I03H" },
                { id = "I03I" },
                { id = "I03J" },
                { id = "I045" },
                { id = "I04P" },
                { id = "I04S" },
                { id = "I04V" }
            }
        })

        NewDropList("library_magic_books_high", {
            rolls = 5,
            list = {
                { id = "I04C" },
                { id = "I04D" },
                { id = "I04E" },
                { id = "I048" },
                { id = "I049" },
                { id = "I04A" },
                { id = "I04B" },
                { id = "I04F" },
                { id = "I04G" },
                { id = "I04H" },
                { id = "I04I" },
                { id = "I04J" },
                { id = "I04K" },
                { id = "I04L" },
                { id = "I04Q" },
                { id = "I04T" },
                { id = "I04W" }
            }
        })


        NewDropList("books_restricted", {
            list = {
                { id = "magic_books_restricted", chance = 5. },
                { id = "rare_books_restricted", chance = 20. },
                { id = "common_books_restricted", chance = 45. },
            }
        })


        NewDropList("books", {
            template = true,
            list = {
                { id = "magic_books", chance = 5. },
                { id = "rare_books", chance = 20. },
                { id = "common_books", chance = 45. },
            }
        })

        NewDropList("keys", {
            max = 2,
            rolls = 2,
            list = {
                { id = "I054", chance = 7. },
                { id = "I053", chance = 20. },
                { id = "I052", chance = 45. },
            }
        })

        NewDropList("common_enemy", {
            template = true,
            max = 2,
            list = {
                { id = "common_item", chance = 4. },
                { id = "consumables", chance = 4. },
                { id = "gems", chance = 1.25 },
                { id = "books_restricted", chance = 8.5 },
                { id = "keys", chance = 1. },
                { id = "unique_items", chance = 0.03 },
                { id = "gold_common", chance = 40. }
            }
        })

        local new_items = MergeTables({}, GetDropList("common_item"))
        NewDropList("adv_item", new_items)
        new_items.quality[1].chance = 15.
        new_items.quality[2].chance = 35.

        NewDropList("adv_enemy", {
            template = true,
            max = 4,
            list = {
                { id = "adv_item", chance = 8.3 },
                { id = "gems", chance = 12. },
                { id = "runes", chance = 7. },
                { id = "consumables", chance = 10. },
                { id = "consumables_potions_strong", chance = 4. },
                { id = "books_restricted", chance = 15. },
                { id = "keys", chance = 3.5 },
                { id = "special_items", chance = 5. },
                { id = "unique_items", chance = 0.05 },
                { id = "gifts", chance = 5.75 },
                { id = "gold_adv", chance = 50. },
            }
        })


        NewDropList("magic_drop", {
            max = 1,
            rolls = 1,
            quality = {
                { quality = MAGIC_ITEM, chance = 100. },
                { quality = MAGIC_ITEM, chance = 100. },
                { quality = MAGIC_ITEM, chance = 100. },
            },
            list = {
                { id = GetGeneratedItemId(SWORD_WEAPON), chance = 100., generate = true, ignore_max = true  },
                { id = GetGeneratedItemId(GREATSWORD_WEAPON), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(AXE_WEAPON), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(GREATAXE_WEAPON), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(BLUNT_WEAPON), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(GREATBLUNT_WEAPON), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(STAFF_WEAPON), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(DAGGER_WEAPON), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(BOW_WEAPON), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(CHEST_ARMOR), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(HEAD_ARMOR), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(HANDS_ARMOR), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(LEGS_ARMOR), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(NECKLACE_JEWELRY), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(RING_JEWELRY), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(SHIELD_OFFHAND), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(ORB_OFFHAND), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(BELT_ARMOR), chance = 100., generate = true, ignore_max = true },
                { id = GetGeneratedItemId(QUIVER_OFFHAND), chance = 100., generate = true, ignore_max = true },
            }
        })

        NewDropList("boss_item", {
            min = 2,
            max = 4,
            rolls = 5,
            quality = {
                { quality = MAGIC_ITEM, chance = 50. },
                { quality = RARE_ITEM, chance = 50. },
                { quality = COMMON_ITEM, chance = 100. },
            },
            list = {
                { id = GetGeneratedItemId(SWORD_WEAPON), chance = 30., generate = true  },
                { id = GetGeneratedItemId(GREATSWORD_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(AXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATAXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATBLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(STAFF_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(DAGGER_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BOW_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(CHEST_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HEAD_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HANDS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(LEGS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(NECKLACE_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(RING_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(SHIELD_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(ORB_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(BELT_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(QUIVER_OFFHAND), chance = 30., generate = true },
            }
        })

        NewDropList("boss_enemy", {
            template = true,
            rolls = 2,
            max = 6,
            list = {
                { id = "boss_item", chance = 38.5 },
                { id = "unique_items", chance = 7. },
                { id = "gems", chance = 33. },
                { id = "runes", chance = 50. },
                { id = "consumables", chance = 11. },
                { id = "consumables_potions_strong", chance = 11. },
                { id = "books", chance = 37. },
                { id = "keys", chance = 50. },
                { id = "shard", chance = 10. },
                { id = "special_items", chance = 10. },
                { id = "gifts", chance = 65. },
                { id = "gold_boss", chance = 70.},
            }
        })


        NewDropList("chest_item", {
            max = 5,
            rolls = 4,
            quality = {
                { quality = MAGIC_ITEM, chance = 15. },
                { quality = RARE_ITEM, chance = 40. },
                { quality = COMMON_ITEM, chance = 100. },
            },
            list = {
                { id = GetGeneratedItemId(SWORD_WEAPON), chance = 30., generate = true  },
                { id = GetGeneratedItemId(GREATSWORD_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(AXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATAXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATBLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(STAFF_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(DAGGER_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BOW_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(CHEST_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HEAD_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HANDS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(LEGS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(NECKLACE_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(RING_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(SHIELD_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(ORB_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(BELT_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(QUIVER_OFFHAND), chance = 30., generate = true },
            }
        })

        NewDropList("crypt_chest_item_low", {
            max = 6,
            rolls = 6,
            quality = {
                { quality = MAGIC_ITEM, chance = 15. },
                { quality = RARE_ITEM, chance = 40. },
                { quality = COMMON_ITEM, chance = 100. },
            },
            list = {
                { id = GetGeneratedItemId(SWORD_WEAPON), chance = 30., generate = true  },
                { id = GetGeneratedItemId(GREATSWORD_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(AXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATAXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATBLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(STAFF_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(DAGGER_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BOW_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(CHEST_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HEAD_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HANDS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(LEGS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(NECKLACE_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(RING_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(SHIELD_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(ORB_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(BELT_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(QUIVER_OFFHAND), chance = 30., generate = true },
            }
        })

        NewDropList("crypt_chest_item_mid", {
            max = 7,
            rolls = 7,
            quality = {
                { quality = MAGIC_ITEM, chance = 20. },
                { quality = RARE_ITEM, chance = 50. },
                { quality = COMMON_ITEM, chance = 100. },
            },
            list = {
                { id = GetGeneratedItemId(SWORD_WEAPON), chance = 30., generate = true  },
                { id = GetGeneratedItemId(GREATSWORD_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(AXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATAXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATBLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(STAFF_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(DAGGER_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BOW_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(CHEST_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HEAD_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HANDS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(LEGS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(NECKLACE_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(RING_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(SHIELD_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(ORB_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(BELT_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(QUIVER_OFFHAND), chance = 30., generate = true },
            }
        })

        NewDropList("crypt_chest_item_high", {
            max = 8,
            rolls = 8,
            quality = {
                { quality = MAGIC_ITEM, chance = 35. },
                { quality = RARE_ITEM, chance = 65. },
                { quality = COMMON_ITEM, chance = 100. },
            },
            list = {
                { id = GetGeneratedItemId(SWORD_WEAPON), chance = 30., generate = true  },
                { id = GetGeneratedItemId(GREATSWORD_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(AXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATAXE_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(GREATBLUNT_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(STAFF_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(DAGGER_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(BOW_WEAPON), chance = 30., generate = true },
                { id = GetGeneratedItemId(CHEST_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HEAD_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(HANDS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(LEGS_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(NECKLACE_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(RING_JEWELRY), chance = 30., generate = true },
                { id = GetGeneratedItemId(SHIELD_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(ORB_OFFHAND), chance = 30., generate = true },
                { id = GetGeneratedItemId(BELT_ARMOR), chance = 30., generate = true },
                { id = GetGeneratedItemId(QUIVER_OFFHAND), chance = 30., generate = true },
            }
        })

        NewDropList("chest", {
            template = true,
            max = 4,
            list = {
                { id = "chest_item", chance = 47.5 },
                { id = "unique_items", chance = 4. },
                { id = "gems", chance = 50. },
                { id = "runes", chance = 30. },
                { id = "consumables", chance = 11. },
                { id = "special_items", chance = 7. },
                { id = "keys", chance = 25. },
                { id = "gifts", chance = 20. },
                { id = "books", chance = 50. },
                { id = "gold_chest", chance = 90.},
            }
        })

        NewDropList("supply_crate", {
            template = true,
            min = 1,
            max = 5,
            list = {
                { id = "chest_item", chance = 65.5 },
                { id = "unique_items", chance = 1. },
                { id = "gems_supply", chance = 75. },
                { id = "runes_supply", chance = 65. },
                { id = "consumables_supply", chance = 20. },
                { id = "books", chance = 50. },
                { id = "keys", chance = 75. },
                { id = "gold_supply", chance = 100.}
            }
        })

        NewDropList("library_books_low", {
            template = true,
            min = 1,
            max = 6,
            list = {
                { id = "library_magic_books_low", chance = 20. },
                { id = "library_rare_books_low", chance = 50. },
                { id = "library_common_books_low", chance = 100. },
            }
        })

        NewDropList("library_books_mid", {
            template = true,
            min = 3,
            max = 10,
            list = {
                { id = "library_magic_books_mid", chance = 30. },
                { id = "library_rare_books_mid", chance = 50. },
                { id = "library_common_books_mid", chance = 100. },
            }
        })

        NewDropList("library_books_high", {
            template = true,
            min = 5,
            max = 14,
            list = {
                { id = "library_magic_books_high", chance = 40. },
                { id = "library_rare_books_high", chance = 65. },
                { id = "library_common_books_high", chance = 100. },
            }
        })

        NewDropList("crypt_chest_low", {
            template = true,
            min = 2,
            max = 5,
            list = {
                { id = "unique_items", chance = 1. },
                { id = "crypt_chest_item_low", chance = 100. },
                { id = "gifts", chance = 15. },
                { id = "runes", chance = 15. },
                { id = "gold_chest", chance = 100. },
            }
        })

        NewDropList("crypt_chest_mid", {
            template = true,
            min = 3,
            max = 7,
            list = {
                { id = "unique_items", chance = 2. },
                { id = "crypt_chest_item_mid", chance = 100. },
                { id = "gifts", chance = 20. },
                { id = "runes", chance = 20. },
                { id = "gold_chest", chance = 100. },
            }
        })

        NewDropList("crypt_chest_high", {
            template = true,
            min = 4,
            max = 9,
            list = {
                { id = "unique_items", chance = 4. },
                { id = "crypt_chest_item_high", chance = 100. },
                { id = "gifts", chance = 25. },
                { id = "runes", chance = 30. },
                { id = "gold_chest", chance = 100. },
            }
        })


        RegisterTestCommand("rnd", function() print(GetRandomReal(0., 100.)) end)


    end

end