---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hatsu.
--- DateTime: 22.11.2025 17:21
---
do

    local DungeonTemplates
    local group
    local Chest_Skins
    local TreasureChestAbility = FourCC("A05E")
    local TreasureCryptAbility = FourCC("A05F")
    local TreasureLibraryAbility = FourCC("A05G")
    local ChestRegion
    local TreasureChestDroplists
    local RESET_TIME = 30.
    local RELOAD_TIME = 360.
    local MIN_MONSTERS = 3
    local MAX_MONSTER = 6
    local ELITE_MONSTERS = 2


    local function GroupEnumFunc()
        if GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) <= 0.045 then
            GroupRemoveUnit(group, GetEnumUnit())
        end
    end

    local function ChestSetup(rect)
        local chest

            GroupEnumUnitsInRect(group, rect, nil)
            ForGroup(group, function() chest = GetEnumUnit() end)
            SetUnitX(chest, GetRectCenterX(rect))
            SetUnitY(chest, GetRectCenterY(rect))
            BlzSetUnitSkin(chest, FourCC(Chest_Skins[GetRandomInt(1, #Chest_Skins)]))
            UnitRemoveAbility(chest, FourCC("A01H"))
            UnitAddAbility(chest, TreasureChestAbility)
            RemoveRect(rect)
            rect = Rect(GetUnitX(chest) - 100., GetUnitY(chest) - 100., GetUnitX(chest) + 100., GetUnitY(chest) + 100.)
            RegionAddRect(ChestRegion, rect)

        return chest
    end

    ---@param unit unit
    ---@return boolean
    function IsNearTreasureChest(unit)
        return IsUnitInRegion(ChestRegion, unit)
    end

    function AreHeroesInDungeon(id)

        for i = 1, 6 do
            if PlayerHero[i] and IsUnitInRegion(DungeonTemplates[id].dungeon_region, PlayerHero[i]) and GetUnitState(PlayerHero[i], UNIT_STATE_LIFE) > 0.045 then
                return true
            end
        end

        return false
    end

    ---@param table table
    function DungeonOpenGate(table)
        for i = 1, #table do
            KillDestructable(table[i])
            SetDestructableAnimation(table[i], "death alternate")
        end
    end

    ---@param table table
    function DungeonCloseGate(table)
        for i = 1, #table do
            DestructableRestoreLife(table[i], 1000., false)
        end
    end

    ---@param dungeon_id string
    function DungeonOpenAllDoors(dungeon_id)
        local template = DungeonTemplates[dungeon_id]

            for i = 1, #template.gates do
                DungeonOpenGate(template.gates[i])
            end

    end

    ---@param dungeon_id string
    function DungeonCloseAllDoors(dungeon_id)
        local template = DungeonTemplates[dungeon_id]

            for i = 1, #template.gates do
                DungeonCloseGate(template.gates[i])
            end

    end


    local function CreateDestructableOcclusionTrigger()
        local destr = GetEnumDestructable()

            if GetDestructableMaxLife(destr) == 1000 then
                local enter_trg = CreateTrigger()
                local leave_trg = CreateTrigger()
                local rect = Rect(GetDestructableX(destr) - 75., GetDestructableY(destr), GetDestructableX(destr) + 75., GetDestructableY(destr) + 350.)

                TriggerRegisterEnterRectSimple(enter_trg, rect)
                TriggerRegisterLeaveRectSimple(leave_trg, rect)

                TriggerAddAction(enter_trg, function()
                    if GetUnitTypeId(GetTriggerUnit()) ~= FourCC("hgry") and GetWidgetLife(destr) > 0. then
                        SetDestructableAnimation(destr, "stand second")
                    end
                end)

                TriggerAddAction(leave_trg, function()
                    GroupClear(group)
                    GroupEnumUnitsInRect(group, rect, nil)
                    ForGroup(group, GroupEnumFunc)
                    if BlzGroupGetSize(group) <= 0 then
                        if GetWidgetLife(destr) > 0. then
                            SetDestructableAnimation(destr, "stand")
                        end
                    end
                end)

            end

    end


    local opened_chest = nil

    local function GetChestNearby()
        if GetUnitAbilityLevel(GetEnumUnit(), TreasureChestAbility) > 0 then
            opened_chest = GetEnumUnit()
        end
    end

    local function ResetChest(chest)
        UnitAddAbility(chest, TreasureChestAbility)
        SetUnitAnimation(chest, "stand")
    end

    function DungeonResetChests(id)
        local template = DungeonTemplates[id]

            if template.treasure_crypt then ResetChest(template.treasure_crypt) end
            if template.treasure_library then ResetChest(template.treasure_library) end

    end

    function OpenTreasureChest(unit, key)
        local key_data = GetItemData(key)

            GroupEnumUnitsInRange(group, GetUnitX(unit), GetUnitY(unit), 250., nil)
            ForGroup(group, GetChestNearby)

            if opened_chest and GetUnitAbilityLevel(opened_chest, TreasureChestAbility) > 0 then
                local chest = opened_chest
                local chest_type = "crypt"

                    UnitRemoveAbility(chest, TreasureChestAbility)
                    SetUnitAnimation(chest, "death")
                    AddSoundVolume("Sounds\\Altar\\chestbig.wav", GetUnitX(chest), GetUnitY(chest), 140, 1800.)

                    if GetUnitAbilityLevel(chest, TreasureLibraryAbility) > 0 then chest_type = "library" end

                    for player = 1, 6 do
                        if PlayerHero[player] then
                            DropDroplistForPlayer(player, GetUnitX(chest), GetUnitY(chest), 75., 150., GetDropList(TreasureChestDroplists[chest_type][key_data.QUALITY]))
                        end
                    end

                if GetItemCharges(key) == 1 then
                    DropItemFromInventory(GetPlayerId(GetOwningPlayer(unit))+1, key, true)
                    RemoveCustomItem(key)
                else
                    SetItemCharges(key, GetItemCharges(key) - 1)
                    UpdateInventoryWindow(GetPlayerId(GetOwningPlayer(unit))+1)
                end

            end

            opened_chest = nil
    end

    local function MonsterSpawner(unit, spawntype, angle, spawn_time)

        ShowUnit(unit, false)
        UnitAddAbility(unit, FourCC("Avul"))

        if spawntype == 1 then

            DelayAction(spawn_time, function()
                local unit_data = GetUnitData(unit)

                    IssuePointOrderById(unit, order_move, GetUnitX(unit) + Rx(150., angle), GetUnitY(unit) + Ry(150., angle))
                    ShowUnit(unit, true)

                    FadeInUnit(unit, 0.6, unit_data.colours, function()
                        SetUnitPathing(unit, true)
                        UnitRemoveAbility(unit, FourCC("Aeth"))
                        UnitRemoveAbility(unit, FourCC("Avul"))
                        unit_data.xp = 0
                        unit_data.classification = 0
                        unit_data.droplist = nil

                        for i = 1, 6 do
                            if PlayerHero[i] and GetUnitState(PlayerHero[i], UNIT_STATE_LIFE) > 0.045 and IsUnitInRange(unit, PlayerHero[i], 2000.) then
                                IssuePointOrderById(unit, order_attack, GetUnitX(PlayerHero[i]), GetUnitY(PlayerHero[i]))
                            end
                        end

                    end)

            end)

        elseif spawntype == 2 then
            local sfx = AddSpecialEffect("Effect\\Void Teleport Red To.mdx", GetUnitX(unit), GetUnitY(unit))

                BlzSetSpecialEffectScale(sfx, BlzGetUnitRealField(unit, UNIT_RF_SCALING_VALUE) * 0.5)
                SafePauseUnit(unit, true)

                    DelayAction(GetRandomReal(0.5, 1.1), function()
                        DestroyEffect(sfx)
                        local teleport_sfx = AddSpecialEffect("Effect\\Void Teleport Red Caster.mdx", GetUnitX(unit), GetUnitY(unit))
                        BlzSetSpecialEffectScale(teleport_sfx, 0.7)
                        DestroyEffect(teleport_sfx)
                        ShowUnit(unit, true)
                        SafePauseUnit(unit, false)
                        UnitRemoveAbility(unit, FourCC("Avul"))
                        local unit_data = GetUnitData(unit)
                        unit_data.xp = 0
                        unit_data.classification = 0
                        unit_data.droplist = nil

                        for i = 1, 6 do
                            if PlayerHero[i] and GetUnitState(PlayerHero[i], UNIT_STATE_LIFE) > 0.045 then
                                IssuePointOrderById(unit, order_attack, GetUnitX(PlayerHero[i]), GetUnitY(PlayerHero[i]))
                            end
                        end

                    end)
        end


    end


    local function SpawnMonsters_AttackPoint(rects, monsterpack, monsters, death_trigger)

        SpawnClearMonsterPack(rects[1].rect, monsters, monsterpack, MIN_MONSTERS, MAX_MONSTER, ELITE_MONSTERS, 8., Player(12))
        DelayAction(0.8, function() ApplyMonsterTraitsToGroup(monsters) end)
        local point_spawn_time = {}

            for i = 1, #rects do
                point_spawn_time[i] = 0.
            end

            ForGroup(monsters, function()
                local monster = GetEnumUnit()
                local var = GetRandomInt(1, #rects)
                local spawnrect = rects[var].rect

                    if rects[var].spawntype == 1 then
                        SetUnitPathing(monster, false)
                        UnitAddAbility(monster, FourCC("Aeth"))
                        SetUnitX(monster, GetRandomRectX(spawnrect))
                        SetUnitY(monster, GetRandomRectY(spawnrect))
                        point_spawn_time[var] = point_spawn_time[var] + 0.1
                    else
                        SetUnitPosition(monster, GetRandomRectX(spawnrect), GetRandomRectY(spawnrect))
                    end

                    TriggerRegisterUnitEvent(death_trigger, monster, EVENT_UNIT_DEATH)
                    MonsterSpawner(monster, rects[var].spawntype, rects[var].angle or 0., point_spawn_time[var])

            end)

    end

    function DungeonClose(id)
        DungeonTemplates[id].is_open = false
        SetUnitAnimation(DungeonTemplates[id].entrance_unit, "morph alternate")
    end

    function DungeonOpen(id)
        DungeonTemplates[id].is_open = true
        SetUnitAnimation(DungeonTemplates[id].entrance_unit, "morph")
        DelayAction(0.833, function() SetUnitAnimation(DungeonTemplates[id].entrance_unit, "stand work") end)
    end

    ---@param id string
    ---@param template table
    function NewDungeonTemplate(id, template)
        DungeonTemplates[id] = template
        local DungeonWaves
        local death_trigger = CreateTrigger()
        local monsterpack
        local spawn = false

        TriggerAddAction(death_trigger, function() GroupRemoveUnit(template.monster_group, GetTriggerUnit()) end)


            DungeonWaves = function()

                if template.current_wave == 0 then
                    TimerStart(template.wave_timer, 1., true, DungeonWaves)
                    template.current_wave = 1
                    monsterpack = template.monsterpacks[GetRandomInt(1, #template.monsterpacks)]
                    SpawnMonsters_AttackPoint(template.monster_spawn_point, monsterpack, template.monster_group, death_trigger)
                    --spawn
                else

                    if BlzGroupGetSize(template.monster_group) == 0 and not spawn then
                        template.current_wave = template.current_wave + 1

                            if template.current_wave > template.max_waves then
                                --end
                                SetUnitAnimation(DungeonTemplates[id].entrance_unit, "stand alternate")
                                DungeonOpenAllDoors(id)

                                for i = 1, 6 do
                                    if PlayerHero[i] and IsUnitInRegion(DungeonTemplates[id].dungeon_region, PlayerHero[i]) then
                                        GiveExpForPlayer(800 + (50 * Current_Wave), i)
                                    end
                                end
                                SendQuestMessage("|c005AFF00"..GetLocalString("Подземелье зачищено", "Dungeon has been cleared").."|r", bj_TEXT_DELAY_QUESTDONE)
                                StartSound(bj_questCompletedSound)

                                TimerStart(template.wave_timer, RELOAD_TIME, false, function()
                                    if AreHeroesInDungeon(id) then
                                        TimerStart(template.wave_timer, 5., true, function()
                                            if not AreHeroesInDungeon(id) then
                                                DungeonResetChests(id)
                                                DungeonCloseAllDoors(id)
                                                template.current_wave = 0
                                                SetUnitAnimation(DungeonTemplates[id].entrance_unit, "stand work")
                                            end
                                        end)
                                    else
                                        DungeonResetChests(id)
                                        DungeonCloseAllDoors(id)
                                        template.current_wave = 0
                                        SetUnitAnimation(DungeonTemplates[id].entrance_unit, "stand work")
                                    end
                                end)
                            else
                                spawn = true
                                DelayAction(4., function() SpawnMonsters_AttackPoint(template.monster_spawn_point, monsterpack, template.monster_group, death_trigger); spawn = false end)
                                --next spawn
                            end
                    elseif not AreHeroesInDungeon(id) and not spawn then
                        --remove all monsters
                        TimerStart(template.wave_timer, 0., false, nil)
                        template.current_wave = 0
                        ForGroup(template.monster_group, function()
                            local unit = GetEnumUnit()
                            SafePauseUnit(unit, true)
                            UnitAddAbility(unit, FourCC("Avul"))
                            VanishUnit(unit, 3., { r = 255, g = 255, b = 255 }, function()
                                ShowUnit(unit, false)
                                KillUnit(unit)
                            end)
                        end)
                        DungeonClose(id)
                        DelayAction(RESET_TIME, function() DungeonOpen(id) end)
                    end

                end

            end

            DungeonTemplates[id].waves_func = DungeonWaves

            if template.occlusion_regions then
                for i = 1, #template.occlusion_regions do
                    EnumDestructablesInRect(template.occlusion_regions[i], nil, CreateDestructableOcclusionTrigger)
                end
            end

            if template.gates then
                for i = 1, #template.gates do
                    local rect = template.gates[i]
                    template.gates[i] = {}

                    EnumDestructablesInRect(rect, nil, function()
                        template.gates[i][#template.gates[i]+1] = GetEnumDestructable()
                    end)

                end
            end

            if template.treasure_crypt then template.treasure_crypt = ChestSetup(template.treasure_crypt) end

            if template.treasure_library then
                template.treasure_library = ChestSetup(template.treasure_library)
                UnitAddAbility(template.treasure_library, TreasureLibraryAbility)
            end

            template.dungeon_region = CreateRegion()
            RegionAddRect(template.dungeon_region, template.dungeon_area)
            template.current_wave = 0
            template.wave_timer = CreateTimer()
            template.monster_group = CreateGroup()
            template.is_open = false
            template.vis_mod = CreateFogModifierRect(Player(0), FOG_OF_WAR_VISIBLE, template.dungeon_area, true, true)

    end

    ---@param id string
    ---@param entrance_npc unit
    function AddDungeonEntrance(id, entrance_npc)
        local trg = CreateTrigger()

            DungeonTemplates[id].entrance_unit = entrance_npc
            CreateNpcData(entrance_npc, "Dungeon")
            AddInteractiveOption(entrance_npc, {
                name = GetLocalString("Войти", "Enter"),
                id = "dungeon_enter",
                feedback = function(clicked, clicking, player)
                    if DungeonTemplates[id].is_open then
                        DisableTrigger(trg)
                        SetUnitX(clicking, GetRectCenterX(DungeonTemplates[id].entrance))
                        SetUnitY(clicking, GetRectCenterY(DungeonTemplates[id].entrance))

                        local minions = GetAllUnitSummonUnits(PlayerHero[GetPlayerId(GetOwningPlayer(GetTriggerUnit()))+1])
                        local x = GetRectCenterX(DungeonTemplates[id].entrance)
                        local y = GetRectCenterY(DungeonTemplates[id].entrance)

                            ForGroup(minions, function()
                                local angle = GetRandomReal(0., 360.)
                                local distance = GetMaxAvailableDistance(x, y, angle, GetRandomReal(150., 450.))
                                SetUnitX(GetEnumUnit(), x + Rx(distance, angle))
                                SetUnitY(GetEnumUnit(), y + Ry(distance, angle))
                            end)

                        DestroyGroup(minions)

                        IssueImmediateOrderById(clicking, order_stop)
                        UnitAddAbility(clicking, FourCC("A05D"))
                        EnableTrigger(trg)
                        FogModifierStart(DungeonTemplates[id].vis_mod)

                        if DungeonTemplates[id].current_wave == 0 then
                            TimerStart(DungeonTemplates[id].wave_timer, 5., false, DungeonTemplates[id].waves_func)
                        end

                        local minimap = BlzGetOriginFrame(ORIGIN_FRAME_MINIMAP, 0)
                        if GetLocalPlayer() == Player(player-1) then
                            SetCameraBoundsToRect(DungeonTemplates[id].dungeon_area)
                            SetDayNightModels("Environment\\DNCDarkNightsLordaeronTerrain.mdx", "Environment\\DNCDarkNightsLordaeronUnit.mdx")
                            BlzFrameSetVisible(minimap, false)
                        end

                    else
                        SimError(GetLocalString("Подземелье закрыто", "The dungeon is closed"), player-1)
                    end
                end }, 1)


                TriggerRegisterEnterRectSimple(trg, DungeonTemplates[id].entrance)
                TriggerAddAction(trg, function()

                        if IsAHero(GetTriggerUnit()) then
                            if GetUnitAbilityLevel(GetTriggerUnit(), FourCC("A05D")) > 0 then
                                UnitRemoveAbility(GetTriggerUnit(), FourCC("A05D"))
                            else
                                local unit = GetTriggerUnit()

                                SetUnitX(unit, GetUnitX(entrance_npc) + GetRandomReal(-75., 75.))
                                SetUnitY(unit, GetUnitY(entrance_npc) - 150.)
                                IssueImmediateOrderById(unit, order_stop)

                                local minions = GetAllUnitSummonUnits(PlayerHero[GetPlayerId(GetOwningPlayer(unit))+1])
                                local x = GetUnitX(unit)
                                local y = GetUnitY(unit)

                                    ForGroup(minions, function()
                                        local angle = GetRandomReal(0., 360.)
                                        local distance = GetMaxAvailableDistance(x, y, angle, GetRandomReal(150., 450.))
                                        SetUnitX(GetEnumUnit(), x + Rx(distance, angle))
                                        SetUnitY(GetEnumUnit(), y + Ry(distance, angle))
                                    end)

                                DestroyGroup(minions)

                                if not AreHeroesInDungeon(id) then
                                    FogModifierStop(DungeonTemplates[id].vis_mod)
                                end

                                local minimap = BlzGetOriginFrame(ORIGIN_FRAME_MINIMAP, 0)
                                if GetLocalPlayer() == GetOwningPlayer(unit) then
                                    SetCameraBoundsToRect(gg_rct_outer_map)
                                    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
                                    BlzFrameSetVisible(minimap, true)
                                end

                            end
                        end
                end)


            local discovery_trigger = CreateTrigger()
            TriggerRegisterUnitInRange(discovery_trigger, entrance_npc, 800., nil)
            TriggerAddAction(discovery_trigger, function()
                if IsAHero(GetTriggerUnit()) and IsUnitVisible(entrance_npc, Player(0)) then
                    CreateMinimapIcon(GetUnitX(entrance_npc), GetUnitY(entrance_npc), 255, 255, 255, "Marker\\MarkDungeon.mdx", FOG_OF_WAR_MASKED)
                    DestroyTrigger(discovery_trigger)
                end
            end)


    end


    function DungeonsInit()
        DungeonTemplates = {}
        group = CreateGroup()
        ChestRegion = CreateRegion()
        Chest_Skins = { "n02A", "n02B", "n02C", "n02D", "n02E" }

        TreasureChestDroplists = {
            ["library"] = { [COMMON_ITEM] = "library_books_low", [RARE_ITEM] = "library_books_mid", [MAGIC_ITEM] = "library_books_high" },
            ["crypt"] = { [COMMON_ITEM] = "crypt_chest_low", [RARE_ITEM] = "crypt_chest_mid", [MAGIC_ITEM] = "crypt_chest_high" }
        }

        NewDungeonTemplate("dungeon_secret_crypt", {
            entrance = gg_rct_Dungeon_1_Entrance,
            gates = {
                gg_rct_Dungeon_1_Crypt, gg_rct_Dungeon_1_Library
            },
            monster_spawn_point = {
                { spawntype = 1, rect = gg_rct_Dungeon_1_Spawner_1, angle = 180. },
                { spawntype = 1, rect = gg_rct_Dungeon_1_Spawner_2, angle = 180. },
                { spawntype = 2, rect = gg_rct_Dungeon_1_Spawner_3 },
                { spawntype = 2, rect = gg_rct_Dungeon_1_Spawner_4 },
            },
            occlusion_regions = { gg_rct_Dungeon_1_occ_1, gg_rct_Dungeon_1_occ_2, gg_rct_Dungeon_1_occ_3, gg_rct_Dungeon_1_occ_4, gg_rct_Dungeon_1_occ_5 },
            treasure_crypt = gg_rct_Dungeon_1_Crypt_chest,
            treasure_library = gg_rct_Dungeon_1_Library_chest,
            dungeon_area = gg_rct_dungeon_1,
            max_waves = 5,
            monsterpacks = { MONSTERPACK_DEMONS, MONSTERPACK_GHOSTS, MONSTERPACK_SKELETONS, MONSTERPACK_ZOMBIES, MONSTERPACK_SUCCUBUS }
        })

        NewDungeonTemplate("dungeon_cave", {
            entrance = gg_rct_Dungeon_2_Entrance,
            gates = {
                gg_rct_Dungeon_2_Crypt, gg_rct_Dungeon_2_Library
            },
            monster_spawn_point = {
                { spawntype = 1, rect = gg_rct_Dungeon_2_Spawner_1, angle = 0. },
                { spawntype = 1, rect = gg_rct_Dungeon_2_Spawner_2, angle = 270. },
                { spawntype = 1, rect = gg_rct_Dungeon_2_Spawner_3, angle = 180. },
            },
            occlusion_regions = { gg_rct_Dungeon_2_occ_1, gg_rct_Dungeon_2_occ_2, gg_rct_Dungeon_2_occ_3, gg_rct_Dungeon_2_occ_4, gg_rct_Dungeon_2_occ_5 },
            treasure_crypt = gg_rct_Dungeon_2_Crypt_chest,
            treasure_library = gg_rct_Dungeon_2_Library_chest,
            dungeon_area = gg_rct_dungeon_2,
            max_waves = 5,
            monsterpacks = { MONSTERPACK_BANDITS, MONSTERPACK_GHOSTS, MONSTERPACK_SKELETONS, MONSTERPACK_ZOMBIES, MONSTERPACK_GOATMEN, MONSTERPACK_ARACHNIDS, MONSTERPACK_SPIDERS }
        })

        NewDungeonTemplate("dungeon_crypt", {
            entrance = gg_rct_Dungeon_3_Entrance,
            gates = {
                gg_rct_Dungeon_3_Library
            },
            monster_spawn_point = {
                { spawntype = 1, rect = gg_rct_Dungeon_3_Spawner_1, angle = 270. },
                { spawntype = 1, rect = gg_rct_Dungeon_3_Spawner_2, angle = 270. },
                { spawntype = 1, rect = gg_rct_Dungeon_3_Spawner_3, angle = 90. },
                { spawntype = 1, rect = gg_rct_Dungeon_3_Spawner_4, angle = 90. },
            },
            occlusion_regions = {
                gg_rct_Dungeon_3_occ_1, gg_rct_Dungeon_3_occ_2, gg_rct_Dungeon_3_occ_3, gg_rct_Dungeon_3_occ_4, gg_rct_Dungeon_3_occ_5, gg_rct_Dungeon_3_occ_6,
                gg_rct_Dungeon_3_occ_7, gg_rct_Dungeon_3_occ_8, gg_rct_Dungeon_3_occ_9, gg_rct_Dungeon_3_occ_10, gg_rct_Dungeon_3_occ_11 },
            treasure_crypt = gg_rct_Dungeon_3_Crypt_chest,
            treasure_library = gg_rct_Dungeon_3_Library_chest,
            dungeon_area = gg_rct_dungeon_3,
            max_waves = 5,
            monsterpacks = { MONSTERPACK_DEMONS, MONSTERPACK_GHOSTS, MONSTERPACK_SKELETONS, MONSTERPACK_ZOMBIES, MONSTERPACK_SUCCUBUS }
        })

        NewDungeonTemplate("dungeon_ancient_ruins", {
            entrance = gg_rct_Dungeon_4_Entrance,
            gates = {
                gg_rct_Dungeon_4_Library, gg_rct_Dungeon_4_Crypt
            },
            monster_spawn_point = {
                { spawntype = 1, rect = gg_rct_Dungeon_4_Spawner_1, angle = 0. },
                { spawntype = 1, rect = gg_rct_Dungeon_4_Spawner_2, angle = 180. },
                { spawntype = 1, rect = gg_rct_Dungeon_4_Spawner_3, angle = 180. },
            },
            occlusion_regions = {
                gg_rct_Dungeon_4_occ_1, gg_rct_Dungeon_4_occ_2, gg_rct_Dungeon_4_occ_3, gg_rct_Dungeon_4_occ_4, gg_rct_Dungeon_4_occ_5, gg_rct_Dungeon_4_occ_6,
                gg_rct_Dungeon_4_occ_7, gg_rct_Dungeon_4_occ_8, gg_rct_Dungeon_4_occ_9 },
            treasure_crypt = gg_rct_Dungeon_4_Crypt_chest,
            treasure_library = gg_rct_Dungeon_4_Library_chest,
            dungeon_area = gg_rct_dungeon_4,
            max_waves = 5,
            monsterpacks = { MONSTERPACK_DEMONS, MONSTERPACK_GHOSTS, MONSTERPACK_SKELETONS, MONSTERPACK_ZOMBIES, MONSTERPACK_SUCCUBUS, MONSTERPACK_GNOLLS, MONSTERPACK_GOATMEN }
        })


        AddDungeonEntrance("dungeon_secret_crypt", gg_unit_n03N_0079)
        AddDungeonEntrance("dungeon_cave", gg_unit_n03O_0076)
        AddDungeonEntrance("dungeon_crypt", gg_unit_n03N_0077)
        AddDungeonEntrance("dungeon_ancient_ruins", gg_unit_n03P_0078)


        DungeonOpen("dungeon_secret_crypt")
        DungeonOpen("dungeon_cave")
        DungeonOpen("dungeon_crypt")
        DungeonOpen("dungeon_ancient_ruins")


        RegisterTestCommand("do", function()
            DungeonOpen("test_dungeon")
            DungeonOpen("dungeon_cave")
        end)

        RegisterTestCommand("dc", function()
            DungeonClose("test_dungeon")
        end)

        RegisterTestCommand("dopen", function()
            DungeonOpenGate(DungeonTemplates["test_dungeon"].gates[1])
            DungeonOpenGate(DungeonTemplates["test_dungeon"].gates[2])
        end)

        RegisterTestCommand("dclose", function()
            DungeonCloseGate(DungeonTemplates["test_dungeon"].gates[1])
            DungeonCloseGate(DungeonTemplates["test_dungeon"].gates[2])
        end)

        RegisterTestCommand("sk", function()
            DungeonTemplates["test_dungeon"].current_wave = 6
            ForGroup(DungeonTemplates["test_dungeon"].monster_group, function()
                KillUnit(GetEnumUnit())
            end)
        end)

    end

end