---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 07.01.2020 18:34
---
do

    ITEM_AFFIX_WORN         = 1
    ITEM_AFFIX_FINE         = 2
    ITEM_AFFIX_EXCELLENT    = 3
    ITEM_AFFIX_IDEAL        = 4

    DECL_HE     = 1
    DECL_SHE    = 2
    DECL_THEY   = 3
    DECL_IT     = 4

    ITEM_SUFFIX_ANGER           = 1
    ITEM_SUFFIX_FURY            = 2
    ITEM_SUFFIX_CONCENTRATION   = 3
    ITEM_SUFFIX_PRECISION       = 4


    QUALITY_ITEM_LIST = {

    }

     QUALITY_STONE_COUNT = {
        [COMMON_ITEM] = {
            rolls = {
                [1] = 35,
                [2] = 25,
                [3] = 15
            }
        },
        [RARE_ITEM] = {
            rolls = {
                [1] = 45,
                [2] = 35,
                [3] = 25
            }
        },
        [UNIQUE_ITEM] = {
            rolls = {
                [1] = 45,
                [2] = 35,
                [3] = 25
            }
        },
        [MAGIC_ITEM] = {
            rolls = {
                [1] = 50,
                [2] = 33,
                [3] = 22,
                [4] = 11
            }
        }
    }


    ITEM_AFFIX_NAME_LIST = {

    }



    ITEM_SUFFIX_LIST = {

    }

     ITEM_QUALITY_SUFFIX_LIST = {
        [COMMON_ITEM] = {
            [SWORD_WEAPON] = {
                ITEM_SUFFIX_ANGER,
                ITEM_SUFFIX_FURY,
                ITEM_SUFFIX_CONCENTRATION,
                ITEM_SUFFIX_PRECISION
            }
        }
    }


    function DefineItemGeneratorTemplates()

        ITEM_AFFIX_NAME_LIST = {
            [ITEM_AFFIX_WORN] = {
                [DECL_HE] = LOCALE_LIST[my_locale]. WORN_DECL_HE,
                [DECL_SHE] = LOCALE_LIST[my_locale]. WORN_DECL_SHE,
                [DECL_THEY] = LOCALE_LIST[my_locale]. WORN_DECL_THEY,
                [DECL_IT] = LOCALE_LIST[my_locale]. WORN_DECL_IT
            },
            [ITEM_AFFIX_FINE] = {
                [DECL_HE] = LOCALE_LIST[my_locale].FINE_DECL_HE,
                [DECL_SHE] = LOCALE_LIST[my_locale].FINE_DECL_SHE,
                [DECL_THEY] = LOCALE_LIST[my_locale].FINE_DECL_THEY,
                [DECL_IT] = LOCALE_LIST[my_locale].FINE_DECL_IT
            },
            [ITEM_AFFIX_EXCELLENT] = {
                [DECL_HE] = LOCALE_LIST[my_locale].EXCELLENT_DECL_HE,
                [DECL_SHE] = LOCALE_LIST[my_locale].EXCELLENT_DECL_SHE,
                [DECL_THEY] = LOCALE_LIST[my_locale].EXCELLENT_DECL_THEY,
                [DECL_IT] = LOCALE_LIST[my_locale].EXCELLENT_DECL_IT
            },
            [ITEM_AFFIX_IDEAL] = {
                [DECL_HE] = LOCALE_LIST[my_locale].IDEAL_DECL_HE,
                [DECL_SHE] = LOCALE_LIST[my_locale].IDEAL_DECL_SHE,
                [DECL_THEY] = LOCALE_LIST[my_locale].IDEAL_DECL_THEY,
                [DECL_IT] = LOCALE_LIST[my_locale].IDEAL_DECL_IT
            }
        }


        QUALITY_ITEM_LIST = {
            [COMMON_ITEM] = {
                [SWORD_WEAPON] = {
                    {
                        icon = "Weapons\\BTNTier1 Sword.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_SWORD_NAME_1,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNAnother Sword.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_SWORD_NAME_2,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNDKSword.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_SWORD_NAME_3,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNSword.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_SWORD_NAME_4,
                        decl = DECL_HE
                    },
                },
                [GREATSWORD_WEAPON] = {
                    {
                        icon = "Weapons\\BTNBarbarian Brutal Slasher.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_GREATSWORD_NAME_1,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNRitual Shaman Knife 1Charge.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_GREATSWORD_NAME_2,
                        decl = DECL_HE
                    },
                },
                [AXE_WEAPON] = {
                    {
                        icon = "Weapons\\BTNBruteAxe.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_AXE_NAME_1,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNGrandAxe.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_AXE_NAME_2,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNSteelAxe.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_AXE_NAME_3,
                        decl = DECL_HE
                    },
                },
                [GREATAXE_WEAPON] = {
                    {
                        icon = "Weapons\\BTNMastercraftBattleaxe.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_GREATAXE_NAME_1,
                        decl = DECL_HE
                    },
                },
                [BLUNT_WEAPON] = {
                    {
                        icon = "Weapons\\BTNAntiqueMace.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BLUNT_NAME_1,
                        decl = DECL_SHE
                    },
                    {
                        icon = "Weapons\\BTNBeatstickV4.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BLUNT_NAME_2,
                        decl = DECL_SHE
                    },
                    {
                        icon = "Weapons\\BTNSpikedClub.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BLUNT_NAME_3,
                        decl = DECL_SHE
                    },
                    {
                        icon = "Weapons\\BTNFlail.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BLUNT_NAME_4,
                        decl = DECL_HE
                    },
                },
                [GREATBLUNT_WEAPON] = {
                    {
                        icon = "Weapons\\BTNMace.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_GREATBLUNT_NAME_1,
                        decl = DECL_SHE
                    },
                    {
                        icon = "Weapons\\BTNMythril Hammer.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_GREATBLUNT_NAME_2,
                        decl = DECL_HE
                    },
                },
                [DAGGER_WEAPON] = {
                    {
                        icon = "Weapons\\BTNDagger.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_DAGGER_NAME_1,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNGoldenDagger.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_DAGGER_NAME_2,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNDagger3.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_DAGGER_NAME_3,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNNastyShiv.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_DAGGER_NAME_4,
                        decl = DECL_SHE
                    },
                    {
                        icon = "Weapons\\BTNMecheteOfFury.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_DAGGER_NAME_5,
                        decl = DECL_HE
                    },
                },
                [STAFF_WEAPON] = {
                    {
                        icon = "Weapons\\BTNEmeraldStaff.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_STAFF_NAME_1,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNFireWand.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_STAFF_NAME_2,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNFrostJade.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_STAFF_NAME_3,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNIce Staff.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_STAFF_NAME_4,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNStick Staff.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_STAFF_NAME_5,
                        decl = DECL_THEY
                    },
                },
                [BOW_WEAPON] = {
                    {
                        icon = "Weapons\\BTNGoldenWoodBow.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BOW_NAME_1,
                        decl = DECL_IT
                    },
                    {
                        icon = "Weapons\\BTNHardBow.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BOW_NAME_2,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNRoughwoodBow.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BOW_NAME_3,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNScoutsBow.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BOW_NAME_4,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNStrongBow.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BOW_NAME_5,
                        decl = DECL_HE
                    },
                    {
                        icon = "Weapons\\BTNWoodenHornBow.blp",
                        name = LOCALE_LIST[my_locale].GENERIC_BOW_NAME_6,
                        decl = DECL_HE
                    },
                },
            },
            [RARE_ITEM] = {},
            [MAGIC_ITEM] = {},
        }


        ITEM_SUFFIX_LIST = {
            [ITEM_SUFFIX_ANGER] = {
                name = LOCALE_LIST[my_locale].ITEM_SUFFIX_ANGER,
                affix_bonus = {
                    [ITEM_AFFIX_WORN] = {
                        max_bonuses = 3,
                        parameter_bonus = {
                            { PARAM = ATTACK_SPEED, value_min = 3, value_max = 5, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 10, value_max = 15, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_DEFENCE, value_min = 5, value_max = 5, METHOD = STRAIGHT_BONUS, probability = 50. }
                        },
                        skill_bonus = {
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00A", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A006", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00C", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_BATTLE_ADVANTAGE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_FINE] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = ATTACK_SPEED, value_min = 5, value_max = 7, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 15, value_max = 17, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_DEFENCE, value_min = 5, value_max = 15, METHOD = STRAIGHT_BONUS, probability = 50. }
                        },
                        skill_bonus = {
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00A", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A006", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00C", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_BATTLE_ADVANTAGE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_EXCELLENT] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = ATTACK_SPEED, value_min = 7, value_max = 11, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 17, value_max = 24, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_DEFENCE, value_min = 15, value_max = 21, METHOD = STRAIGHT_BONUS, probability = 50. }
                        },
                        skill_bonus = {
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00A", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A006", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00C", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_BATTLE_ADVANTAGE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_IDEAL] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = ATTACK_SPEED, value_min = 11, value_max = 15, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 24, value_max = 30, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_DEFENCE, value_min = 21, value_max = 35, METHOD = STRAIGHT_BONUS, probability = 50. }
                        },
                        skill_bonus = {
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00A", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A006", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00C", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_BATTLE_ADVANTAGE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    }
                }
            },
            [ITEM_SUFFIX_FURY] = {
                name = LOCALE_LIST[my_locale].ITEM_SUFFIX_FURY,
                affix_bonus = {
                    [ITEM_AFFIX_WORN] = {
                        max_bonuses = 3,
                        parameter_bonus = {
                            { PARAM = CRIT_CHANCE, value_min = 5, value_max = 5, METHOD = STRAIGHT_BONUS, probability = 60. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 10, value_max = 14, METHOD = STRAIGHT_BONUS, probability = 40. },
                        },
                        skill_bonus = {
                            { id = "A00B", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00Q", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00O", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_INNER_STRENGTH, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_FINE] = {
                        max_bonuses = 3,
                        parameter_bonus = {
                            { PARAM = CRIT_CHANCE, value_min = 5, value_max = 7, METHOD = STRAIGHT_BONUS, probability = 60. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 14, value_max = 18, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = STR_STAT, value_min = 1, value_max = 1, METHOD = STRAIGHT_BONUS, probability = 10. },
                        },
                        skill_bonus = {
                            { id = "A00B", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00Q", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00O", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_INNER_STRENGTH, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_EXCELLENT] = {
                        max_bonuses = 3,
                        parameter_bonus = {
                            { PARAM = CRIT_CHANCE, value_min = 7, value_max = 9, METHOD = STRAIGHT_BONUS, probability = 60. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 18, value_max = 20, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = STR_STAT, value_min = 1, value_max = 2, METHOD = STRAIGHT_BONUS, probability = 10. },
                        },
                        skill_bonus = {
                            { id = "A00B", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00Q", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00O", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_INNER_STRENGTH, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_IDEAL] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = CRIT_CHANCE, value_min = 9, value_max = 11, METHOD = STRAIGHT_BONUS, probability = 60. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 20, value_max = 25, METHOD = STRAIGHT_BONUS, probability = 70. },
                            { PARAM = STR_STAT, value_min = 1, value_max = 2, METHOD = STRAIGHT_BONUS, probability = 15. },
                        },
                        skill_bonus = {
                            { id = "A00B", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00Q", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00O", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_INNER_STRENGTH, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    }
                }
            },
            [ITEM_SUFFIX_CONCENTRATION] = {
                name = LOCALE_LIST[my_locale].ITEM_SUFFIX_CONCENTRATION,
                affix_bonus = {
                    [ITEM_AFFIX_WORN] = {
                        max_bonuses = 3,
                        parameter_bonus = {
                            { PARAM = MAGICAL_ATTACK, value_min = 10, value_max = 11, METHOD = STRAIGHT_BONUS, probability = 70. },
                            { PARAM = MAGICAL_SUPPRESSION, value_min = 5, value_max = 7, METHOD = STRAIGHT_BONUS, probability = 70. },
                            { PARAM = HP_REGEN, value_min = 5, value_max = 6, METHOD = STRAIGHT_BONUS, probability = 20. },
                        },
                        skill_bonus = {
                            { id = "A00H", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00E", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00N", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00L", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ICE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIRE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_LIGHTNING, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_FINE] = {
                        max_bonuses = 3,
                        parameter_bonus = {
                            { PARAM = MAGICAL_ATTACK, value_min = 11, value_max = 14, METHOD = STRAIGHT_BONUS, probability = 75. },
                            { PARAM = MAGICAL_SUPPRESSION, value_min = 7, value_max = 10, METHOD = STRAIGHT_BONUS, probability = 60. },
                            { PARAM = HP_REGEN, value_min = 6, value_max = 8, METHOD = STRAIGHT_BONUS, probability = 20. },
                        },
                        skill_bonus = {
                            { id = "A00H", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00E", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00N", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00L", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ICE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIRE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_LIGHTNING, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_EXCELLENT] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = MAGICAL_ATTACK, value_min = 14, value_max = 18, METHOD = STRAIGHT_BONUS, probability = 75. },
                            { PARAM = MAGICAL_SUPPRESSION, value_min = 10, value_max = 14, METHOD = STRAIGHT_BONUS, probability = 60. },
                            { PARAM = HP_REGEN, value_min = 8, value_max = 10, METHOD = STRAIGHT_BONUS, probability = 20. },
                        },
                        skill_bonus = {
                            { id = "A00H", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00E", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00N", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00L", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { category = SKILL_CATEGORY_ICE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIRE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_LIGHTNING, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_IDEAL] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = MAGICAL_ATTACK, value_min = 18, value_max = 22, METHOD = STRAIGHT_BONUS, probability = 80. },
                            { PARAM = MAGICAL_SUPPRESSION, value_min = 14, value_max = 19, METHOD = STRAIGHT_BONUS, probability = 60. },
                            { PARAM = HP_REGEN, value_min = 10, value_max = 11, METHOD = STRAIGHT_BONUS, probability = 20. },
                        },
                        skill_bonus = {
                            { id = "A00H", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00E", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00N", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00L", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { category = SKILL_CATEGORY_ICE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIRE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_LIGHTNING, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    }
                }
            },
            [ITEM_SUFFIX_PRECISION] = {
                name = LOCALE_LIST[my_locale].ITEM_SUFFIX_PRECISION,
                affix_bonus = {
                    [ITEM_AFFIX_WORN] = {
                        max_bonuses = 3,
                        parameter_bonus = {
                            { PARAM = CRIT_MULTIPLIER, value_min = 0.1, value_max = 0.1, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = MAGICAL_ATTACK, value_min = 10, value_max = 15, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 12, value_max = 17, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = ALL_RESIST, value_min = 2, value_max = 3, METHOD = STRAIGHT_BONUS, probability = 50. },
                        },
                        skill_bonus = {
                            { id = "A00H", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00E", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00N", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00L", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A001", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00F", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00D", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00M", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00K", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A003", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00G", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00J", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A005", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },

                            { id = "A00B", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00Q", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00Z", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00P", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A008", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A009", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A006", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00A", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00O", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00C", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_BATTLE_ADVANTAGE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_INNER_STRENGTH, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ICE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIRE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_LIGHTNING, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ARCANE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_FINE] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = CRIT_MULTIPLIER, value_min = 0.1, value_max = 0.2, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = MAGICAL_ATTACK, value_min = 15, value_max = 18, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 17, value_max = 22, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = ALL_RESIST, value_min = 3, value_max = 4, METHOD = STRAIGHT_BONUS, probability = 50. },
                        },
                        skill_bonus = {
                            { id = "A00H", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00E", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00N", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00L", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A001", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00F", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00D", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00M", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00K", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A003", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00G", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00J", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A005", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },

                            { id = "A00B", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00Q", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00Z", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00P", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A008", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A009", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A006", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00A", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00O", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { id = "A00C", bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_BATTLE_ADVANTAGE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_INNER_STRENGTH, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ICE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIRE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_LIGHTNING, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ARCANE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_EXCELLENT] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = CRIT_MULTIPLIER, value_min = 0.2, value_max = 0.3, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = MAGICAL_ATTACK, value_min = 18, value_max = 22, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 22, value_max = 26, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = ALL_RESIST, value_min = 4, value_max = 5, METHOD = STRAIGHT_BONUS, probability = 50. },
                        },
                        skill_bonus = {
                            { id = "A00H", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00E", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00N", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00L", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A001", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00F", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00D", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00M", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00K", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A003", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00G", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00J", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A005", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },

                            { id = "A00B", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00Q", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00Z", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00P", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A008", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A009", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A006", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00A", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00O", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { id = "A00C", bonus_levels_min = 1, bonus_levels_max = 2,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_BATTLE_ADVANTAGE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_INNER_STRENGTH, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ICE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIRE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_LIGHTNING, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ARCANE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    },
                    [ITEM_AFFIX_IDEAL] = {
                        max_bonuses = 4,
                        parameter_bonus = {
                            { PARAM = CRIT_MULTIPLIER, value_min = 0.3, value_max = 0.45, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = MAGICAL_ATTACK, value_min = 22, value_max = 28, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = PHYSICAL_ATTACK, value_min = 26, value_max = 33, METHOD = STRAIGHT_BONUS, probability = 50. },
                            { PARAM = ALL_RESIST, value_min = 5, value_max = 7, METHOD = STRAIGHT_BONUS, probability = 50. },
                        },
                        skill_bonus = {
                            { id = "A00H", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00E", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00N", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00L", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A001", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00F", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00D", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00M", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00K", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A003", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00G", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00J", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A005", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },

                            { id = "A00B", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00Q", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00Z", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A010", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00P", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A007", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A008", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A009", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A006", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00A", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00O", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { id = "A00C", bonus_levels_min = 1, bonus_levels_max = 3,  probability = 10. },
                            { category = SKILL_CATEGORY_FIGHTING_MASTERY, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_BATTLE_ADVANTAGE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_INNER_STRENGTH, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ICE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_FIRE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_LIGHTNING, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. },
                            { category = SKILL_CATEGORY_ARCANE, bonus_levels_min = 1, bonus_levels_max = 1,  probability = 10. }
                        },
                        effect_bonus = {

                        }
                    }
                }
            }
        }

    end

end