---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 17.02.2020 19:42
---
do


    LegendaryEffectsList = 0



    function GetLegendaryEffect(id)
        return LegendaryEffectsList[id]
    end


    function NewLegendaryEffect(template)
        LegendaryEffectsList[template.id] = template
    end



    function ApplyLegendaryEffect(unit, effect, flag)
        local unit_data = GetUnitData(unit)

            if effect.type == ITEM_PASSIVE_EFFECT then
                if flag then
                    if effect.on_apply and not unit_data.effects[effect.id] then effect.on_apply(unit) end
                    --unit_data.effects[effect.id] = true
                    UnitAddEffect(unit, effect.id)
                else
                    if effect.on_end and unit_data.effects[effect.id] then effect.on_end(unit) end
                    UnitRemoveEffect(unit, effect.id)
                    --unit_data.effects[effect.id] = nil
                end
            else
                --if flag then
                    --UnitAddEffect(unit, effect.id)
                --else
                    --UnitRemoveEffect(unit, effect.id)
               -- end

                if flag and not unit_data.effects[effect.id] then
                    unit_data.effects[effect.id] = CreateTimer()
                    TimerStart(unit_data.effects[effect.id], effect.period, true, function()
                        effect.periodic(unit)
                    end)
                elseif not flag and unit_data.effects[effect.id] then
                    effect.on_end(unit)
                    DestroyTimer(unit_data.effects[effect.id])
                    unit_data.effects[effect.id] = nil
                end
            end

    end
    

    function InitLegendaryEffects()
        LegendaryEffectsList = {}
        --=========================================================================
        NewLegendaryEffect({
            name =  LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_FIREBOND,
            id = "FRBD",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_CRYSTAL_AXE,
            id = "ECRA",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_PAIN_ECHO,
            id = "PNEC",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_BOOT_OF_COWARD,
            id = "BTCW",
            type = ITEM_ACTIVE_EFFECT,
            period = 0.75,
            periodic = function(unit)

                if GetUnitState(unit, UNIT_STATE_LIFE) <= 0.045 then
                    RemoveBuff(unit, "A01Q")
                else
                    local enemies = CreateGroup()

                    GroupEnumUnitsInRange(enemies, GetUnitX(unit), GetUnitY(unit), 400., nil)

                        for index = BlzGroupGetSize(enemies) - 1, 0, -1 do
                            local picked = BlzGroupUnitAt(enemies, index)
                            if not IsUnitEnemy(picked, GetOwningPlayer(unit)) or GetUnitState(picked, UNIT_STATE_LIFE) <= 0.045 then
                                GroupRemoveUnit(enemies, picked)
                            end
                        end

                    local count = BlzGroupGetSize(enemies)

                    if GetUnitAbilityLevel(unit, FourCC("A01Q")) == 0 and count > 0 then ApplyBuff(unit, unit, "A01Q", BlzGroupGetSize(enemies))
                    elseif GetUnitAbilityLevel(unit, FourCC("A01Q")) > 0 and count > 0 then SetBuffLevel(unit, "A01Q", BlzGroupGetSize(enemies)); SetBuffExpirationTime(unit, "A01Q", -1)
                    else RemoveBuff(unit, "A01Q") end

                    GroupClear(enemies)
                    DestroyGroup(enemies)
                end

            end,
            on_end = function(unit)
                RemoveBuff(unit, "A01Q")
            end
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_WITCH_MASTERY,
            id = "EWTM",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_EYE_OF_THE_STORM,
            id = "EOTS",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_BOOSTERS,
            id = "BSTR",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_MASTER_OF_ELEMENTS,
            id = "MOFE",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_RITUAL_DAGGER,
            id = "RDAG",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================
        NewLegendaryEffect({
            name = LOCALE_LIST[my_locale].ITEM_LEG_DESCRIPTION_ICE_TOUCH,
            id = "ITCH",
            type = ITEM_PASSIVE_EFFECT
        })
        --=========================================================================

    end


end