---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 13.06.2022 4:18
---
do

    RUNEWORD_TEMPLATE_DATA = 0


    function GetRunewordData(id)
        return RUNEWORD_TEMPLATE_DATA[id]
    end


    function NewRuneword(template)
        RUNEWORD_TEMPLATE_DATA[#RUNEWORD_TEMPLATE_DATA+1] = template
    end


    ---@param id string
    ---@param rune_id string
    ---@return boolean
    function IsPartOfRuneword(id, rune_id)

            for i = 1, #RUNEWORD_TEMPLATE_DATA[id].runeword do
                if RUNEWORD_TEMPLATE_DATA[id].runeword[i] == rune_id then
                    return true
                end
            end

        return false
    end

    --4/8/12/16
    ---@param stone_slots table
    ---@return string
    function GetRunewordId(stone_slots)
        local word = ""

            for i = 1, #stone_slots do
                if stone_slots[i] then
                    word = word .. stone_slots[i].raw
                end
            end


            if #word < 12 then
                return nil
            end

            for i = 1, #RUNEWORD_TEMPLATE_DATA do
                local runeword = RUNEWORD_TEMPLATE_DATA[i].runeword[1] .. RUNEWORD_TEMPLATE_DATA[i].runeword[2] .. RUNEWORD_TEMPLATE_DATA[i].runeword[3]
                local start_index = 1

                    for var = 1, 2 do

                        if string.sub(word, start_index, start_index + 11) == runeword then
                            return i
                        end

                        start_index = start_index + 4
                    end

            end

        return nil
    end


    function InitRunewords()

        RUNEWORD_TEMPLATE_DATA = {}


        NewRuneword({
            name = GetLocalString("Ярость", "Rage"),
            runeword = { ITEM_RUNE_FEH, ITEM_RUNE_RAIDO, ITEM_RUNE_KANO },
            [ITEM_TYPE_WEAPON] = {
                BONUS = {
                    { PARAM = CRIT_MULTIPLIER, VALUE = 0.3, METHOD = STRAIGHT_BONUS },
                    { PARAM = ATTACK_SPEED, VALUE = 20, METHOD = STRAIGHT_BONUS },
                    { PARAM = STR_STAT, VALUE = 15, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Мир", "Peace"),
            runeword = { ITEM_RUNE_SOL, ITEM_RUNE_DAG, ITEM_RUNE_EHW },
            [ITEM_TYPE_ARMOR] = {
                BONUS = {
                    { PARAM = ALL_RESIST, VALUE = 15, METHOD = STRAIGHT_BONUS },
                    { PARAM = MP_VALUE, VALUE = 75, METHOD = STRAIGHT_BONUS },
                    { PARAM = INT_STAT, VALUE = 15, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Благоразумие", "Prudence"),
            runeword = { ITEM_RUNE_GEBO, ITEM_RUNE_ISA, ITEM_RUNE_DAG },
            [ITEM_TYPE_JEWELRY] = {
                BONUS = {
                    { PARAM = PHYSICAL_DEFENCE, VALUE = 150, METHOD = STRAIGHT_BONUS },
                    { PARAM = CONTROL_REDUCTION, VALUE = 20, METHOD = STRAIGHT_BONUS },
                    { PARAM = VULNERABILITY, VALUE = -10, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Ужас", "Dread"),
            runeword = { ITEM_RUNE_BER, ITEM_RUNE_DAG, ITEM_RUNE_ISA },
            [ITEM_TYPE_WEAPON] = {
                BONUS = {
                    { PARAM = HP_PER_HIT, VALUE = 15, METHOD = STRAIGHT_BONUS },
                    { PARAM = CAST_SPEED, VALUE = 18, METHOD = STRAIGHT_BONUS },
                    { PARAM = DARKNESS_BONUS, VALUE = 60, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Быстрота", "Quickness"),
            runeword = { ITEM_RUNE_RAIDO, ITEM_RUNE_FEH, ITEM_RUNE_BER },
            [ITEM_TYPE_ARMOR] = {
                BONUS = {
                    { PARAM = LIGHTNING_BONUS, VALUE = 60, METHOD = STRAIGHT_BONUS },
                    { PARAM = ATTACK_SPEED, VALUE = 20, METHOD = STRAIGHT_BONUS },
                    { PARAM = MANACOST, VALUE = -2, METHOD = STRAIGHT_BONUS },
                    { PARAM = MOVING_SPEED, VALUE = 1.15, METHOD = MULTIPLY_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Чистота", "Purity"),
            runeword = { ITEM_RUNE_SOL, ITEM_RUNE_KANO, ITEM_RUNE_EHW },
            [ITEM_TYPE_JEWELRY] = {
                BONUS = {
                    { PARAM = BONUS_DEMON_DAMAGE, VALUE = 44, METHOD = STRAIGHT_BONUS },
                    { PARAM = BONUS_BEAST_DAMAGE, VALUE = 44, METHOD = STRAIGHT_BONUS },
                    { PARAM = BONUS_HUMAN_DAMAGE, VALUE = 44, METHOD = STRAIGHT_BONUS },
                    { PARAM = BONUS_UNDEAD_DAMAGE, VALUE = 44, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Жадность", "Greed"),
            runeword = { ITEM_RUNE_ISA, ITEM_RUNE_DAG, ITEM_RUNE_GEBO },
            [ITEM_TYPE_JEWELRY] = {
                BONUS = {
                    { PARAM = BONUS_BEAST_DAMAGE, VALUE = 35, METHOD = STRAIGHT_BONUS },
                    { PARAM = DROP_BONUS, VALUE = 15, METHOD = STRAIGHT_BONUS },
                    { PARAM = GOLD_BONUS, VALUE = 25, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Обморожение", "Frostbite"),
            runeword = { ITEM_RUNE_GEBO, ITEM_RUNE_SOL, ITEM_RUNE_FEH },
            [ITEM_TYPE_WEAPON] = {
                BONUS = {
                    { PARAM = ICE_BONUS, VALUE = 60, METHOD = STRAIGHT_BONUS },
                    { PARAM = MELEE_DAMAGE_REDUCTION, VALUE = 12, METHOD = STRAIGHT_BONUS },
                    { PARAM = ICE_RESIST, VALUE = 40, METHOD = STRAIGHT_BONUS },
                    { PARAM = CRIT_MULTIPLIER, VALUE = 0.1, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Угли", "Embers"),
            runeword = { ITEM_RUNE_KANO, ITEM_RUNE_FEH, ITEM_RUNE_DAG },
            [ITEM_TYPE_WEAPON] = {
                BONUS = {
                    { PARAM = FIRE_BONUS, VALUE = 60, METHOD = STRAIGHT_BONUS },
                    { PARAM = MAGICAL_ATTACK, VALUE = 140, METHOD = STRAIGHT_BONUS },
                    { PARAM = FIRE_RESIST, VALUE = 40, METHOD = STRAIGHT_BONUS },
                    { PARAM = CRIT_CHANCE, VALUE = 17, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Заряженный", "Charged"),
            runeword = { ITEM_RUNE_RAIDO, ITEM_RUNE_DAG, ITEM_RUNE_GEBO },
            [ITEM_TYPE_WEAPON] = {
                BONUS = {
                    { PARAM = LIGHTNING_BONUS, VALUE = 60, METHOD = STRAIGHT_BONUS },
                    { PARAM = CAST_SPEED, VALUE = 18, METHOD = STRAIGHT_BONUS },
                    { PARAM = LIGHTNING_RESIST, VALUE = 40, METHOD = STRAIGHT_BONUS },
                    { PARAM = RANGE_DAMAGE_REDUCTION, VALUE = 7, METHOD = STRAIGHT_BONUS },
                },
            },
        })

        NewRuneword({
            name = GetLocalString("Непробиваемый", "Unpenetrable"),
            runeword = { ITEM_RUNE_DAG, ITEM_RUNE_GEBO, ITEM_RUNE_FEH },
            [ITEM_TYPE_ARMOR] = {
                BONUS = {
                    { PARAM = BLOCK_CHANCE, VALUE = 20, METHOD = STRAIGHT_BONUS },
                    { PARAM = MELEE_DAMAGE_REDUCTION, VALUE = 12, METHOD = STRAIGHT_BONUS },
                    { PARAM = RANGE_DAMAGE_REDUCTION, VALUE = 12, METHOD = STRAIGHT_BONUS },
                    { PARAM = HP_VALUE, VALUE = 150, METHOD = STRAIGHT_BONUS },
                },
            },
        })

    end

end