---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 20.05.2022 15:17
---
do


    local AmbientData


    function InitAmbient()


        AmbientData = {
            {
                rects = {
                    gg_rct_amb_event_1_1,
                    gg_rct_amb_event_1_2
                },
                events = {
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\breath1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath6.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath7.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath8.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath9.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -50, key_income_min = 1, key_income_max = 3,
                        min_offset = 100., max_offset = 1300.
                    },
                }
            },
            {
                rects = {
                    gg_rct_amb_event_2_1
                },
                events = {
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\frog1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\frog2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\frog3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\frog4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\frog5.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -10, key_income_min = 3, key_income_max = 5,
                        min_offset = 100., max_offset = 500.
                    },
                }
            },
            {
                rects = {
                    gg_rct_amb_event_3_1
                },
                events = {
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\wind1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind6.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind7.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind8.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind9.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -10, key_income_min = 1, key_income_max = 5,
                        min_offset = 100., max_offset = 300.
                    },
                }
            },
            {
                rects = {
                    gg_rct_amb_event_4_1
                },
                events = {
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\scream1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream7.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -20, key_income_min = 1, key_income_max = 3,
                        min_offset = 100., max_offset = 700.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\wind1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind6.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind7.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind8.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind9.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -10, key_income_min = 1, key_income_max = 7,
                        min_offset = 50., max_offset = 700.
                    },
                }
            },
            {
                rects = {
                    gg_rct_amb_event_5_1
                },
                events = {
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\scream1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream7.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -20, key_income_min = 1, key_income_max = 3,
                        min_offset = 100., max_offset = 700.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\birdienight1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight5.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 7, key_trigger_penalty = -10, key_income_min = 2, key_income_max = 4,
                        min_offset = 50., max_offset = 300., time_of_day_min = 20., time_of_day_max = 7.
                    },
                }
            },
            {
                rects = {
                    gg_rct_amb_event_6_1
                },
                events = {
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\wind1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind6.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind7.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind8.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\wind9.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -30, key_income_min = 1, key_income_max = 7,
                        min_offset = 50., max_offset = 1000.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\scream1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream7.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -20, key_income_min = 1, key_income_max = 3,
                        min_offset = 100., max_offset = 1000.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\birdienight1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight5.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 7, key_trigger_penalty = -10, key_income_min = 2, key_income_max = 4,
                        min_offset = 50., max_offset = 1000., time_of_day_min = 20., time_of_day_max = 7.
                    },
                }
            },
            {
                rects = {
                    gg_rct_amb_event_7_1
                },
                events = {
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\breath1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath6.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath7.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath8.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath9.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -50, key_income_min = 1, key_income_max = 4,
                        min_offset = 100., max_offset = 700.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\scream1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream7.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -40, key_income_min = 1, key_income_max = 5,
                        min_offset = 100., max_offset = 700.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\birdienight1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight5.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 7, key_trigger_penalty = -10, key_income_min = 2, key_income_max = 4,
                        min_offset = 50., max_offset = 700., time_of_day_min = 20., time_of_day_max = 7.
                    },
                }
            },
            {
                rects = {
                    gg_rct_rift_loc_7
                },
                events = {
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\breath1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath6.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath7.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath8.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\breath9.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -50, key_income_min = 1, key_income_max = 4,
                        min_offset = 100., max_offset = 1500.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\scream1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream3.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream5.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\scream7.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 12, key_trigger_penalty = -40, key_income_min = 1, key_income_max = 5,
                        min_offset = 100., max_offset = 1500.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\birdienight1.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight2.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight4.flac", volume = 128, cutoff = 1600. },
                            { sound = "Sound\\Ambient\\Event\\birdienight5.flac", volume = 128, cutoff = 1600. },
                        },
                        key = 7, key_trigger_penalty = -10, key_income_min = 2, key_income_max = 4,
                        min_offset = 50., max_offset = 1300., time_of_day_min = 20., time_of_day_max = 7.
                    },
                    {
                        list = {
                            { sound = "Sound\\Ambient\\Event\\singlecricket.flac", volume = 120, cutoff = 1300. }
                        },
                        key = 12, key_trigger_penalty = -30, key_income_min = 3, key_income_max = 6,
                        min_offset = 50., max_offset = 500.
                    }
                }
            }
        }


        for i = 1, #AmbientData do
            local ambient_event = AmbientData[i]
            ambient_event.timer = CreateTimer()

                TimerStart(ambient_event.timer, 2., true, function()
                    for event = 1, #ambient_event.events do
                        ambient_event.events[event].key = ambient_event.events[event].key + GetRandomInt(ambient_event.events[event].key_income_min, ambient_event.events[event].key_income_max)

                        if Chance(ambient_event.events[event].key) then
                            local trigger = true

                            if ambient_event.events[event].time_of_day_min then
                                local time = GetTimeOfDay()

                                if not (time >= ambient_event.events[event].time_of_day_min and time <= ambient_event.events[event].time_of_day_max) then
                                    trigger = false
                                end
                            end

                            if trigger then
                                ambient_event.events[event].key = ambient_event.events[event].key_trigger_penalty
                                local rnd = GetRandomInt(1, #ambient_event.events[event].list)
                                local rect = ambient_event.rects[GetRandomInt(1, #ambient_event.rects)]
                                local xoffset = GetRandomReal(ambient_event.events[event].min_offset, ambient_event.events[event].max_offset)
                                local yoffset = GetRandomReal(ambient_event.events[event].min_offset, ambient_event.events[event].max_offset)

                                if GetRandomInt(1, 2) then xoffset = -xoffset end
                                if GetRandomInt(1, 2) then yoffset = -yoffset end

                                local point_x = GetRandomReal(GetRectMinX(rect), GetRectMaxX(rect)) + xoffset
                                local point_y = GetRandomReal(GetRectMinY(rect), GetRectMaxY(rect)) + yoffset

                                local vision = CreateFogModifierRadius(Player(8), FOG_OF_WAR_VISIBLE, point_x, point_y, 32., true, false)
                                FogModifierStart(vision)
                                AddSoundVolume(ambient_event.events[event].list[rnd].sound, point_x, point_y, ambient_event.events[event].list[rnd].volume, ambient_event.events[event].list[rnd].cutoff, ambient_event.events[event].list[rnd].distance or 4000.)
                                DelayAction(0., function()
                                    FogModifierStop(vision)
                                    DestroyFogModifier(vision)
                                end)
                                break
                            end

                        end

                    end
                end)

        end


    end

end