---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hatsu.
--- DateTime: 06.11.2025 22:47
---
do

    GamblerFrame = nil
    local LeaveTrigger = 0
    local EnterTrigger = 0
    local ClickTrigger = 0
    local last_EnteredFrame
    local last_EnteredFrameTimer
    local GamblerStock
    local item_table
    local unique_item_pool
    local quality_chances
    local BASE_COST = 1500
    local COST_PER_LEVEL = 25
    local RANDOM_COST_MOD = 225


    ---@param button_type number
    ---@param texture string
    ---@param size_x real
    ---@param size_y real
    ---@param relative_frame framehandle
    ---@param frame_point_from framepointtype
    ---@param frame_point_to framepointtype
    ---@param offset_x real
    ---@param offset_y real
    ---@param parent_frame framehandle
    local function NewButton(button_type, texture, size_x, size_y, relative_frame, frame_point_from, frame_point_to, offset_x, offset_y, parent_frame)
        local new_Frame = BlzCreateFrame('ScriptDialogButton', parent_frame, 0, 0)
        local new_FrameImage = BlzCreateFrameByType("BACKDROP", "ButtonIcon", new_Frame, "", 0)
        local new_FrameBorder = BlzCreateFrameByType("BACKDROP", "ButtonBorder", new_FrameImage, "", 0)

        ButtonList[new_Frame] = {
            button_type = button_type,
            item = nil,
            button = new_Frame,
            image = new_FrameImage,
            original_texture = texture,
        }

        FrameRegisterNoFocus(new_Frame)
        FrameRegisterClick(new_Frame, texture)

        BlzTriggerRegisterFrameEvent(ClickTrigger, new_Frame, FRAMEEVENT_CONTROL_CLICK)
        BlzTriggerRegisterFrameEvent(EnterTrigger, new_Frame, FRAMEEVENT_MOUSE_ENTER)
        BlzTriggerRegisterFrameEvent(LeaveTrigger, new_Frame, FRAMEEVENT_MOUSE_LEAVE)


        BlzFrameSetSize(new_FrameBorder, size_x, size_y)
        BlzFrameSetTexture(new_FrameBorder, "UI\\inventory_frame.blp", 0, true)
        BlzFrameSetAllPoints(new_FrameBorder, new_FrameImage)

        BlzFrameSetPoint(new_Frame, frame_point_from, relative_frame, frame_point_to, offset_x, offset_y)
        BlzFrameSetSize(new_Frame, size_x, size_y)
        BlzFrameSetTexture(new_FrameImage, texture, 0, true)
        BlzFrameSetAllPoints(new_FrameImage, new_Frame)

        return new_Frame
    end


    function UpdateGamblerStock()

       for i = 1, #GamblerStock do
           local item_data = ITEM_TEMPLATE_DATA[FourCC(GamblerStock[i])]

                item_data.level = Current_Wave + GetRandomInt(0, 3)
                item_data.cost = math.floor(BASE_COST + (item_data.level * COST_PER_LEVEL)) + GetRandomInt(-RANDOM_COST_MOD, RANDOM_COST_MOD)

       end

    end


    local function BuyGamblerItem(player, item)
        local template = ITEM_TEMPLATE_DATA[FourCC(item)]
        local gold = GetPlayerState(Player(player-1), PLAYER_STATE_RESOURCE_GOLD)
        local total_cost = template.cost + template.sell_value

            if CountFreeBagSlots(player) <= 0 then
                Feedback_InventoryNoSpace(player)
                return false
            end

            if gold >= total_cost then
                local item_id
                local newitem
                local item_data
                local quality = COMMON_ITEM

                    for i = 1, #quality_chances do
                        if Chance(quality_chances[i].chance) then

                            quality = quality_chances[i].quality

                            if quality == UNIQUE_ITEM or quality == SET_ITEM then

                                if unique_item_pool[quality][template.SUBTYPE] then
                                    item_id = unique_item_pool[quality][template.SUBTYPE][GetRandomInt(1, #unique_item_pool[quality][template.SUBTYPE])]
                                    break
                                end
                            else
                                item_id = item_table[item]
                                break
                            end

                        end
                    end


                    newitem = CreateCustomItem_Id(FourCC(item_id), 0., 0., quality)
                    item_data = GetItemData(newitem)

                    GenerateItemLevel(newitem, template.level)
                    SetPlayerState(Player(player-1), PLAYER_STATE_RESOURCE_GOLD, gold - total_cost)

                    AddToInventory(player, newitem)
                    if item_data.soundpack and item_data.soundpack.drop then PlayLocalSound(item_data.soundpack.drop, player-1, 128) end
                    PlayLocalSound("Abilities\\Spells\\Items\\ResourceItems\\ReceiveGold.wav", player-1)
                    DestroyEffect(AddSpecialEffectTarget("UI\\Feedback\\GoldCredit\\GoldCredit.mdx", gg_unit_n03M_0024, "origin"))
                return true
            else
                Feedback_NoGold(player)
            end

        return false
    end

    local function Slot_Clicked()
        local player = GetPlayerId(GetTriggerPlayer()) + 1
        local h = BlzGetTriggerFrame()
        --local item_data = GetItemData(ButtonList[h].item)

            if ButtonList[h].item then
                CreatePlayerContextMenu(player, ButtonList[h].button, FRAMEPOINT_RIGHT, GamblerFrame[player].masterframe)
                AddContextOption(player, LOCALE_LIST[my_locale].UI_TEXT_BUY, function()
                    BuyGamblerItem(player, ButtonList[h].item)
                end)
            else
                DestroyContextMenu(player)
            end

    end


    local function EnterAction()
        local player = GetPlayerId(GetTriggerPlayer()) + 1
        local h = BlzGetTriggerFrame()


        TimerStart(last_EnteredFrameTimer[player], GLOBAL_TOOLTIP_FADE_TIME, false, function()
            GamblerFrame[player].in_focus = nil
            RemoveTooltip(player)
            last_EnteredFrame[player] = nil
        end)


        if last_EnteredFrame[player] == h then
            return
        else
            GamblerFrame[player].in_focus = nil
            RemoveTooltip(player)
        end

        last_EnteredFrame[player] = h

            if ButtonList[h].item then
                GamblerFrame[player].in_focus = ButtonList[h]
                ShowSpecialTooltip(ButtonList[h].item, GamblerFrame[player].tooltip, ButtonList[h], player)
            else
                GamblerFrame[player].in_focus = nil
                RemoveTooltip(player)
            end

    end

    local function LeaveAction()
        local player = GetPlayerId(GetTriggerPlayer()) + 1
        GamblerFrame[player].in_focus = nil
        RemoveTooltip(player)
    end


    function UpdateGamblerWindow()
        for player = 1, 6 do
            if GamblerFrame[player].state then
                for i = 1, #GamblerStock do
                    local item_data = ITEM_TEMPLATE_DATA[FourCC(GamblerStock[i])]
                    local button_data = GetButtonData(GamblerFrame[player].slot[i])
                        FrameChangeTexture(button_data.button, item_data.frame_texture)
                        BlzFrameSetTexture(button_data.image, item_data.frame_texture, 0, true)
                        button_data.item = GamblerStock[i]
                end
            end
        end
    end

    function ReloadGamblerFrames()
        for player = 1, 6 do DrawGamblerUI(player) end
        UpdateGamblerWindow()
    end

    function DrawGamblerUI(player)

            local main_frame = BlzCreateFrame('EscMenuBackdrop', GAME_UI, 0, 0)

                BlzFrameSetPoint(main_frame, FRAMEPOINT_TOPLEFT, GAME_UI, FRAMEPOINT_TOPLEFT, 0.01, -0.05)
                BlzFrameSetSize(main_frame, 0.24, 0.323)

            local new_Frame = BlzCreateFrame('EscMenuBackdrop', main_frame, 0, 0)
                BlzFrameSetPoint(new_Frame, FRAMEPOINT_BOTTOMRIGHT, main_frame, FRAMEPOINT_BOTTOMRIGHT, -0.02, 0.02)
                BlzFrameSetPoint(new_Frame, FRAMEPOINT_BOTTOMLEFT, main_frame, FRAMEPOINT_BOTTOMLEFT, 0.02, 0.02)
                BlzFrameSetPoint(new_Frame, FRAMEPOINT_TOPRIGHT, main_frame, FRAMEPOINT_TOPRIGHT, -0.02, -0.07)
                BlzFrameSetPoint(new_Frame, FRAMEPOINT_TOPLEFT, main_frame, FRAMEPOINT_TOPLEFT, 0.02, -0.07)
                GamblerFrame[player].inventory_border = new_Frame

                GamblerFrame[player].slot[1] = NewButton(INV_SLOT, "GUI\\inventory_slot.blp", 0.04, 0.04, new_Frame, FRAMEPOINT_TOPLEFT, FRAMEPOINT_TOPLEFT, 0.02, -0.017, new_Frame)

                            for i = 2, 4 do
                                GamblerFrame[player].slot[i] = NewButton(INV_SLOT, "GUI\\inventory_slot.blp", 0.04, 0.04, GamblerFrame[player].slot[i - 1], FRAMEPOINT_TOPLEFT, FRAMEPOINT_TOPRIGHT, 0., 0., new_Frame)
                            end

                            for row = 2, 5 do
                                for i = 1, 4 do
                                    local slot = i + ((row - 1) * 4)
                                    GamblerFrame[player].slot[slot] = NewButton(INV_SLOT, "GUI\\inventory_slot.blp", 0.04, 0.04, GamblerFrame[player].slot[slot - 4], FRAMEPOINT_TOP, FRAMEPOINT_BOTTOM, 0., 0., new_Frame)
                                end
                            end

                GamblerFrame[player].slot[21] = BlzCreateFrameByType("BACKDROP", "ButtonIcon", new_Frame, "", 0)
                BlzFrameSetAllPoints(GamblerFrame[player][21], new_Frame)
                BlzFrameSetAlpha(GamblerFrame[player][21], 0)

                new_Frame = BlzCreateFrameByType('BACKDROP', "PORTRAIT", main_frame, "",0)
                BlzFrameSetPoint(new_Frame, FRAMEPOINT_TOPLEFT, main_frame, FRAMEPOINT_TOPLEFT, 0.02, -0.02)
                BlzFrameSetSize(new_Frame, 0.0435, 0.0435)
                GamblerFrame[player].portrait = new_Frame

                local border = BlzCreateFrameByType("BACKDROP", "aaa", GamblerFrame[player].portrait, "", 0)
                BlzFrameSetSize(border, 1., 1.)
                BlzFrameSetTexture(border, "UI\\inventory_frame.blp", 0, true)
                BlzFrameSetAllPoints(border, GamblerFrame[player].portrait)

                new_Frame = BlzCreateFrameByType("TEXT", "shop name", GamblerFrame[player].portrait, "", 0)
                BlzFrameSetPoint(new_Frame, FRAMEPOINT_LEFT, GamblerFrame[player].portrait, FRAMEPOINT_RIGHT, 0.011, 0.)
                BlzFrameSetTextAlignment(new_Frame, TEXT_JUSTIFY_MIDDLE, TEXT_JUSTIFY_LEFT)
                BlzFrameSetScale(new_Frame, 1.35)

                GamblerFrame[player].name = new_Frame
                GamblerFrame[player].main_frame = main_frame
                GamblerFrame[player].masterframe = BlzCreateFrameByType("BACKDROP", "ButtonIcon", GamblerFrame[player].slot[21], "", 0)
                GamblerFrame[player].tooltip = NewTooltip(GamblerFrame[player].masterframe)
                BlzFrameSetVisible(GamblerFrame[player].main_frame, false)
                GamblerFrame[player].state = false

    end


    function InitGambler()
        GamblerFrame = {}
        last_EnteredFrame = {}
        last_EnteredFrameTimer = {}

        GamblerStock = {
            "rd01", "rd02", "rd03", "rd04", "rd05", "rd06", "rd07", "rd08", "rd09", "rd10", "rd11", "rd12", "rd17", "rd14", "rd15", "rd16", "rd13", "rd18", "rd19"
        }

        item_table = {
            ["rd01"] = "IGJN",
            ["rd02"] = "IGJR",
            ["rd03"] = "IGSO",
            ["rd04"] = "IGST",
            ["rd05"] = "IGAO",
            ["rd06"] = "IGAT",
            ["rd07"] = "IGBO",
            ["rd08"] = "IGBT",
            ["rd09"] = "IGDR",
            ["rd10"] = "IGSF",
            ["rd11"] = "IGBW",
            ["rd12"] = "IGAB",
            ["rd13"] = "IGOS",
            ["rd14"] = "IGAL",
            ["rd15"] = "IGAC",
            ["rd16"] = "IGAD",
            ["rd17"] = "IGAH",
            ["rd18"] = "IGOO",
            ["rd19"] = "IGOQ",
        }

        unique_item_pool = {
            [UNIQUE_ITEM] = {
                [RING_JEWELRY]      = { "I02F", "I01C", "I037", "I03Y", "I04X" },
                [NECKLACE_JEWELRY]  = { "I019", "I02X" },
                [LEGS_ARMOR]        = { "I00O", "I018", "I03T", "I040", "I04M" },
                [HANDS_ARMOR]       = { "I01W", "I03Z", "I047", "I04N" },
                [HEAD_ARMOR]        = { "I00Q", "I02Q", "I041", "I050", "I01L" },
                [CHEST_ARMOR]       = { "I00S", "I03U" },
                [STAFF_WEAPON]      = { "I00P", "I02R", "I03A" },
                [DAGGER_WEAPON]     = { "I00R", "I04Z" },
                [SWORD_WEAPON]      = { "I042" },
                [GREATSWORD_WEAPON] = { "I02E", "I02S" },
                [AXE_WEAPON]        = { "I00T", "I01D" },
                [GREATBLUNT_WEAPON] = { "I043" },
                [BLUNT_WEAPON]      = { "I051" },
                [BOW_WEAPON]        = { "I00N" },
                [ORB_OFFHAND]       = { "I02G", "I01J" },
            },
            [SET_ITEM] = {
                [RING_JEWELRY]      = { "I01B" },
                [NECKLACE_JEWELRY]  = { "I01A" },
                [HANDS_ARMOR]       = { "I02L" },
                [LEGS_ARMOR]        = { "I01E", "I02K" },
                [CHEST_ARMOR]       = { "I01F", "I02I" },
                [HEAD_ARMOR]        = { "I01G", "I02J"},
                [BLUNT_WEAPON]      = { "I01H" },
                [DAGGER_WEAPON]     = { "I01I" },
            }
        }

        quality_chances = {
            { chance = 0.05, quality = UNIQUE_ITEM },
            { chance = 0.1, quality = SET_ITEM },
            { chance = 10., quality = MAGIC_ITEM },
            { chance = 89., quality = RARE_ITEM },
            { chance = 100., quality = COMMON_ITEM },
        }

        for i = 1, 6 do
            last_EnteredFrameTimer[i] = CreateTimer()
        end

        for player = 1, 6 do
            GamblerFrame[player] = {}
            GamblerFrame[player].slot = {}
        end

        local soundpack = {
            open = { "Units\\Orc\\Headhunter\\HeadhunterWhat2.wav", "Units\\Orc\\Headhunter\\HeadhunterWhat3.wav", "Units\\Orc\\Headhunter\\HeadhunterPissed1.wav", "Units\\Orc\\Headhunter\\HeadhunterYes2.wav" },
            close = { "Units\\Orc\\Headhunter\\HeadhunterYes1.wav", "Units\\Orc\\Headhunter\\HeadhunterYes3.wav", "Units\\Orc\\Headhunter\\HeadhunterYes4.wav" },
        }


        CreateNpcData(gg_unit_n03M_0024, GetLocalString("ЛеТролль", "LeTroll"))
        AddSpecialEffectTarget("Marker\\VendorIcon.mdx", gg_unit_n03M_0024, "overhead")
        AddInteractiveOption(gg_unit_n03M_0024, { name = GetLocalString("Торговать", "Trade"), id = "trade_conv", feedback = function(clicked, clicking, player)
            local id = player - 1

                if player <= 6 then


                        if GetLocalPlayer() == Player(id) then BlzFrameSetVisible(GamblerFrame[player].main_frame, true) end
                        GamblerFrame[player].state = true
                        BlzFrameSetTexture(GamblerFrame[player].portrait, "NPC\\BTNTrollTrickster.blp", 0, true)
                        BlzFrameSetText(GamblerFrame[player].name, GetUnitName(clicked))
                        UpdateGamblerWindow()

                        SetUIState(player, SKILL_PANEL, false)
                        SetUIState(player, CHAR_PANEL, false)
                        SetUIState(player, TALENT_PANEL, false)

                        if soundpack then
                            PlayLocalSound(soundpack.open[GetRandomInt(1, #soundpack.open)], id, 125)
                        end

                            local timer = CreateTimer()
                            TimerStart(timer, 0.1, true, function()
                                if not IsUnitInRange(clicking, clicked, 250.) or GetUnitState(clicking, UNIT_STATE_LIFE) < 0.045 then
                                    GamblerFrame[player].in_focus = nil
                                    DestroySlider(player)
                                    DestroyContextMenu(player)
                                    GamblerFrame[player].state = false
                                    TimerStart(last_EnteredFrameTimer[player], 0., false, nil)
                                    if GetLocalPlayer() == Player(id) then BlzFrameSetVisible(GamblerFrame[player].main_frame, false) end
                                    DestroyTimer(GetExpiredTimer())
                                    if soundpack then
                                        PlayLocalSound(soundpack.close[GetRandomInt(1, #soundpack.close)], id, 125)
                                    end
                                end
                            end)

                    end

        end })

        UpdateGamblerStock()

        LeaveTrigger = CreateTrigger()
        EnterTrigger = CreateTrigger()
        ClickTrigger = CreateTrigger()
        TriggerAddAction(EnterTrigger, EnterAction)
        --TriggerAddAction(LeaveTrigger, LeaveAction)
        TriggerAddAction(ClickTrigger, Slot_Clicked)
    end

end