---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 17.06.2022 19:30
---
do


    SacrificeAltarFrame = 0


    local function NewButton(texture, size_x, size_y, relative_frame, frame_point_from, frame_point_to, offset_x, offset_y, parent_frame)
        local new_Frame = BlzCreateFrame('ScriptDialogButton', parent_frame, 0, 0)
        local new_FrameImage = BlzCreateFrameByType("BACKDROP", "ButtonIcon", new_Frame, "", 0)
        local new_FrameBorder = BlzCreateFrameByType("BACKDROP", "ButtonBorder", new_Frame, "", 0)

            ButtonList[new_Frame] = {
                frame = new_Frame, image = new_FrameImage, hex_button = nil
            }

            FrameRegisterNoFocus(new_Frame)
            BlzFrameSetPoint(new_Frame, frame_point_from, relative_frame, frame_point_to, offset_x, offset_y)
            BlzFrameSetSize(new_Frame, size_x, size_y)
            BlzFrameSetTexture(new_FrameImage, texture, 0, true)
            FrameRegisterClick(new_Frame, texture)
            BlzFrameSetAllPoints(new_FrameImage, new_Frame)

            BlzFrameSetTexture(new_FrameBorder, "DiabolicUI_Button_64x64_Border.tga", 0, true)
            BlzFrameSetPoint(new_FrameBorder, FRAMEPOINT_TOPRIGHT, new_Frame, FRAMEPOINT_TOPRIGHT, 0.00, 0.00)
            BlzFrameSetPoint(new_FrameBorder, FRAMEPOINT_BOTTOMLEFT, new_Frame, FRAMEPOINT_BOTTOMLEFT, 0.00, 0.00)

            --BlzTriggerRegisterFrameEvent(ClickTrigger, new_Frame, FRAMEEVENT_CONTROL_CLICK)
            --BlzTriggerRegisterFrameEvent(EnterTrigger, new_Frame, FRAMEEVENT_MOUSE_ENTER)
            --BlzTriggerRegisterFrameEvent(LeaveTrigger, new_Frame, FRAMEEVENT_MOUSE_LEAVE)

        return new_Frame
    end

    local function NewButtonWithCharges(texture, size_x, size_y, relative_frame, frame_point_from, frame_point_to, offset_x, offset_y, parent_frame)
        local new_Frame = BlzCreateFrame('ScriptDialogButton', parent_frame, 0, 0)
        local new_FrameImage = BlzCreateFrameByType("BACKDROP", "ButtonIcon", new_Frame, "", 0)
        local new_FrameCharges = BlzCreateFrameByType("BACKDROP", "ButtonCharges", new_Frame, "", 0)
        local new_FrameChargesText = BlzCreateFrameByType("TEXT", "ButtonChargesText", new_FrameCharges, "", 0)
        local new_FrameBorder = BlzCreateFrameByType("BACKDROP", "ButtonBorder", new_Frame, "", 0)

            ButtonList[new_Frame] = {
                frame = new_Frame, image = new_FrameImage, charges_frame = new_FrameCharges, charges_text_frame = new_FrameChargesText, hex = nil
            }

            FrameRegisterNoFocus(new_Frame)
            BlzFrameSetPoint(new_Frame, frame_point_from, relative_frame, frame_point_to, offset_x, offset_y)
            BlzFrameSetSize(new_Frame, size_x, size_y)
            BlzFrameSetTexture(new_FrameImage, texture, 0, true)
            FrameRegisterClick(new_Frame, texture)
            BlzFrameSetAllPoints(new_FrameImage, new_Frame)

            --BlzFrameSetAllPoints(border, new_Frame)

            BlzFrameSetPoint(new_FrameCharges, FRAMEPOINT_BOTTOMRIGHT, new_FrameImage, FRAMEPOINT_BOTTOMRIGHT, -0.002, 0.002)
            BlzFrameSetSize(new_FrameCharges, 0.01, 0.01)
            BlzFrameSetTexture(new_FrameCharges, "GUI\\ChargesTexture.blp", 0, true)
            BlzFrameSetPoint(new_FrameChargesText, FRAMEPOINT_CENTER, new_FrameCharges, FRAMEPOINT_CENTER, 0.,0.)
            BlzFrameSetText(new_FrameChargesText, "")

            BlzFrameSetTexture(new_FrameBorder, "DiabolicUI_Button_64x64_Border.tga", 0, true)
            BlzFrameSetPoint(new_FrameBorder, FRAMEPOINT_TOPRIGHT, new_Frame, FRAMEPOINT_TOPRIGHT, 0.00, 0.00)
            BlzFrameSetPoint(new_FrameBorder, FRAMEPOINT_BOTTOMLEFT, new_Frame, FRAMEPOINT_BOTTOMLEFT, 0.00, 0.00)

            --BlzTriggerRegisterFrameEvent(ClickTrigger, new_Frame, FRAMEEVENT_CONTROL_CLICK)
            --BlzTriggerRegisterFrameEvent(EnterTrigger, new_Frame, FRAMEEVENT_MOUSE_ENTER)
            --BlzTriggerRegisterFrameEvent(LeaveTrigger, new_Frame, FRAMEEVENT_MOUSE_LEAVE)

        return new_Frame
    end


    local function DrawUI(player)
        local new_Frame
        local main_frame = BlzCreateFrame('EscMenuBackdrop', GAME_UI, 0, 0)

            SacrificeAltarFrame[player].main = main_frame

            BlzFrameSetPoint(main_frame, FRAMEPOINT_TOPLEFT, GAME_UI, FRAMEPOINT_TOPLEFT, 0.01, -0.05)
            BlzFrameSetSize(main_frame, 0.288, 0.24)

            new_Frame = BlzCreateFrameByType('BACKDROP', "PORTRAIT", main_frame, "",0)
            BlzFrameSetPoint(new_Frame, FRAMEPOINT_TOPLEFT, main_frame, FRAMEPOINT_TOPLEFT, 0.02, -0.02)
            BlzFrameSetSize(new_Frame, 0.0435, 0.0435)
            SacrificeAltarFrame[player].portrait = new_Frame

            new_Frame = BlzCreateFrameByType("TEXT", "shop name", SacrificeAltarFrame[player].portrait, "", 0)
            BlzFrameSetPoint(new_Frame, FRAMEPOINT_LEFT, SacrificeAltarFrame[player].portrait, FRAMEPOINT_RIGHT, 0.011, 0.)
            BlzFrameSetTextAlignment(new_Frame, TEXT_JUSTIFY_MIDDLE, TEXT_JUSTIFY_LEFT)
            BlzFrameSetScale(new_Frame, 1.35)
            SacrificeAltarFrame[player].name = new_Frame



            new_Frame = BlzCreateFrame('EscMenuBackdrop', main_frame, 0, 0)
            BlzFrameSetPoint(new_Frame, FRAMEPOINT_BOTTOMRIGHT, main_frame, FRAMEPOINT_BOTTOMRIGHT, -0.015, 0.015)
            BlzFrameSetPoint(new_Frame, FRAMEPOINT_BOTTOMLEFT, main_frame, FRAMEPOINT_BOTTOMLEFT, 0.015, 0.015)
            BlzFrameSetSize(new_Frame, 0.28, 0.16)
            --RegisterConstructor(main_frame, 0.3, 0.24, 0.01)
            SacrificeAltarFrame[player].backdrop = new_Frame

            new_Frame = BlzCreateFrame('EscMenuBackdrop', main_frame, 0, 0)
            BlzFrameSetPoint(new_Frame, FRAMEPOINT_TOPRIGHT, SacrificeAltarFrame[player].backdrop, FRAMEPOINT_TOPRIGHT, -0.015, -0.015)
            BlzFrameSetPoint(new_Frame, FRAMEPOINT_TOPLEFT, SacrificeAltarFrame[player].backdrop, FRAMEPOINT_TOPLEFT, 0.015, -0.015)
            BlzFrameSetSize(new_Frame, 0.12, 0.07)
            SacrificeAltarFrame[player].upper_backdrop = new_Frame
            --RegisterConstructor(SacrificeAltarFrame[player].upper_backdrop, 0.12, 0.06, 0.01)


            SacrificeAltarFrame[player].hex_button[1] = NewButtonWithCharges("ReplaceableTextures\\CommandButtons\\BTNPeon.blp", 0.036, 0.036, SacrificeAltarFrame[player].upper_backdrop, FRAMEPOINT_LEFT, FRAMEPOINT_LEFT, 0.018, 0., SacrificeAltarFrame[player].upper_backdrop)

            for i = 2, 5 do
                SacrificeAltarFrame[player].hex_button[i] = NewButtonWithCharges("ReplaceableTextures\\CommandButtons\\BTNPeon.blp", 0.036, 0.036, SacrificeAltarFrame[player].hex_button[i-1], FRAMEPOINT_LEFT, FRAMEPOINT_RIGHT, 0.0034, 0., SacrificeAltarFrame[player].upper_backdrop)
            end

            new_Frame = BlzCreateFrame('EscMenuBackdrop', main_frame, 0, 0)
            BlzFrameSetPoint(new_Frame, FRAMEPOINT_BOTTOMRIGHT, SacrificeAltarFrame[player].backdrop, FRAMEPOINT_BOTTOMRIGHT, -0.015, 0.015)
            BlzFrameSetPoint(new_Frame, FRAMEPOINT_BOTTOMLEFT, SacrificeAltarFrame[player].backdrop, FRAMEPOINT_BOTTOMLEFT, 0.015, 0.015)
            BlzFrameSetSize(new_Frame, 0.12, 0.07)
            SacrificeAltarFrame[player].bottom_backdrop = new_Frame

            SacrificeAltarFrame[player].cancel_hex_button[1] = NewButton("ReplaceableTextures\\CommandButtons\\BTNCancel.blp", 0.036, 0.036, SacrificeAltarFrame[player].bottom_backdrop, FRAMEPOINT_LEFT, FRAMEPOINT_LEFT, 0.018, 0., SacrificeAltarFrame[player].bottom_backdrop)

            for i = 2, 5 do
                SacrificeAltarFrame[player].cancel_hex_button[i] = NewButton("ReplaceableTextures\\CommandButtons\\BTNCancel.blp", 0.036, 0.036, SacrificeAltarFrame[player].cancel_hex_button[i-1], FRAMEPOINT_LEFT, FRAMEPOINT_RIGHT, 0.0034, 0., SacrificeAltarFrame[player].bottom_backdrop)
            end

            if GetLocalPlayer() ~= Player(player-1) then
                BlzFrameSetVisible(main_frame, false)
            end

    end


    function ReloadSacrificeAltarFrame()
        for player = 1, 6 do DrawUI(player) end
    end


    function BuildSacrificeAltarUI()
        SacrificeAltarFrame = {}

            for player = 1, 6 do
                SacrificeAltarFrame[player] = {}
                SacrificeAltarFrame[player].hex_button = {}
                SacrificeAltarFrame[player].cancel_hex_button = {}
                DrawUI(player)
            end


    end

    RegisterTestCommand("sa", function()
        BuildSacrificeAltarUI()
    end)


    function InitSacrificeAltar()


    end

end