---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 24.05.2022 16:51
---
do


    function SplitterLegendaryEffect(source, target)
        local starting_angle = GetRandomReal(0., 359.)
        local angle_window = 360. / 7

            for i = 1, 7 do
                local missile = ThrowMissile(source, nil, "splitter_missile", nil, GetUnitX(target), GetUnitY(target), 0.,0., starting_angle)
                starting_angle = starting_angle + angle_window
                GroupAddUnit(missile.hit_group, target)
            end
    end

end