---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI.
--- DateTime: 06.09.2021 0:56
---
do


    function RevenantLaserMissile(caster, missile)
        local timer = CreateTimer()
        local group = CreateGroup()
        local second_group = CreateGroup()
        local hit_group = CreateGroup()
        local radius = 50.
        local half_radius = radius / 3.
        local range_steps = math.ceil(300. / half_radius) + 1
        local starting_angle = missile.heading_angle + 90.

            TimerStart(timer, 0.025, true, function()
                if missile.time > 0. then
                    local step_x = missile.current_x - Rx(150., starting_angle); local step_y = missile.current_y - Ry(150., starting_angle)

                    for i = 1, range_steps do
                        GroupEnumUnitsInRange(group, step_x, step_y, radius, nil)
                        for index = BlzGroupGetSize(group) - 1, 0, -1 do
                            GroupAddUnit(second_group, BlzGroupUnitAt(group, index))
                        end
                        step_x = step_x + Rx(half_radius, starting_angle)
                        step_y = step_y + Ry(half_radius, starting_angle)
                    end

                    for index = BlzGroupGetSize(second_group) - 1, 0, -1 do
                        local picked = BlzGroupUnitAt(second_group, index)
                        if IsUnitEnemy(picked, MONSTER_PLAYER) and GetUnitState(picked, UNIT_STATE_LIFE) > 0.045 and GetUnitAbilityLevel(picked, FourCC("Avul")) == 0 and not IsUnitInGroup(picked, hit_group) then
                            ApplyEffect(caster, picked, 0.,0., "revenant_lightning_effect", Current_Wave)
                            GroupAddUnit(hit_group, picked)
                            DelayAction(0.2, function() if hit_group then GroupRemoveUnit(hit_group, picked) end end)
                        end
                    end

                    GroupClear(second_group)

                else
                    DestroyGroup(group)
                    DestroyGroup(hit_group)
                    DestroyGroup(second_group)
                    DestroyTimer(timer)
                end
            end)

    end



    function CastReanimate(caster)
        local angle = GetRandomReal(0., 359.)
        local max_range = GetMaxAvailableDistance(GetUnitX(caster), GetUnitY(caster), angle, GetRandomReal(200., 500.))
        local point_x = GetUnitX(caster) + Rx(max_range, angle)
        local point_y = GetUnitY(caster) + Ry(max_range, angle)

            DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Undead\\RaiseSkeletonWarrior\\RaiseSkeleton.mdx", point_x, point_y))
            local reanimated = CreateUnit(SECOND_MONSTER_PLAYER, FourCC("u00G"), point_x, point_y, angle)
            SetUnitAnimation(reanimated, "birth")
            SafePauseUnit(reanimated, true)
            UnitAddAbility(reanimated, FourCC("Avul"))
            DelayAction(2.333, function()
                UnitApplyTimedLife(reanimated, 0, 16.)
                SafePauseUnit(reanimated, false)
                UnitRemoveAbility(reanimated, FourCC("Avul"))
            end)

    end


    function CreateVoidRain(caster, x, y, radius, duration)
        local timer = CreateTimer()

            TimerStart(timer, 0.23, true, function()
                if duration < 0 then
                    DestroyTimer(timer)
                else
                    duration = duration - 0.23
                    local impact_angle = GetRandomReal(0., 359.)
                    local impact_offset = GetRandomReal(0., radius / 2.)
                    local impact_x, impact_y = x + Rx(impact_offset, impact_angle), y + Ry(impact_offset, impact_angle)
                    local missile = ThrowMissile(caster, nil, "void_rain_missile", nil, impact_x + 100., impact_y - 100., impact_x, impact_y, 0.)
                    BlzSetSpecialEffectPitch(missile.my_missile, (AngleBetweenXY_DEG(200., 800., 0., 0.) - 180.) * bj_DEGTORAD)
                end
            end)

    end


    function CreateFireRain(caster, x, y, radius, duration)
        local timer = CreateTimer()

        local sound = CreateNew3DSound("Abilities\\Spells\\Demon\\RainOfFire\\RainOfFireLoop1.wav", x, y, 35., 100, 1500.)
        StartSound(sound)

            TimerStart(timer, 0.18, true, function()
                if duration < 0 then
                    StopSound(sound, true, false)
                    DestroyTimer(timer)
                else
                    duration = duration - 0.18
                    local impact_angle = GetRandomReal(0., 359.)
                    local impact_offset = GetRandomReal(0., radius / 2.)
                    local impact_x, impact_y = x + Rx(impact_offset, impact_angle), y + Ry(impact_offset, impact_angle)
                    ApplyEffect(caster, nil, impact_x, impact_y, "fire_rain_effect", 1)
                    --local missile = ThrowMissile(caster, nil, "fire_rain_missile", nil, impact_x + 125., impact_y - 125., impact_x, impact_y, 0.)
                    --BlzSetSpecialEffectPitch(missile.my_missile, (AngleBetweenXY_DEG(125., 800., 0., 0.) - 180.) * bj_DEGTORAD)
                end
            end)

    end


    function CastVoidDisc(caster, x, y)
        local sfx = AddSpecialEffect("Effect\\Void Disc.mdx", x, y)
        local timer = CreateTimer()
        local duration = 4.

            TimerStart(timer, 0.33, true, function()
                if duration < 0. then
                    DestroyTimer(timer)
                    DestroyEffect(sfx)
                else
                    duration = duration - 0.33
                    ApplyEffect(caster, nil, x, y, "EVDS", Current_Wave)
                end
            end)

    end

end