---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hatsu.
--- DateTime: 11.10.2025 0:07
---
do


    local GloomreedGathered
    local GloomreedLocations
    local GloomreedStage
    local GloomreedTimer
    local GloomreedId



    function EnableGloomreedSpawn()

        if not (TimerGetTimeout(GloomreedTimer) > 0) then
            TimerStart(GloomreedTimer, 360., true, function()

                for i = 1, #GloomreedLocations do
                    local count = 0

                        EnumItemsInRect(GloomreedLocations[i], nil, function()
                            if GetItemTypeId(GetEnumItem()) == GloomreedId then count = 1 end
                        end)

                        if count == 0 then
                            for i2 = 1, GetRandomInt(1, 3) do
                                CreateItem(GloomreedId, GetRandomReal(GetRectMinX(GloomreedLocations[i]), GetRectMaxX(GloomreedLocations[i])), GetRandomReal(GetRectMinY(GloomreedLocations[i]), GetRectMaxY(GloomreedLocations[i])))
                            end
                        end
                end

                for player = 1, 6 do
                    if GloomreedStage[player] == 1 then
                        return
                    end
                end

                TimerStart(GloomreedTimer, 0, false, nil)

            end)
        end

    end


    function EnableInfectedQuest()
        UnlockInteractiveOptionId(Estrid, "estrid_infected_start_conv")
        BlzPlaySpecialEffect(EstridData.questmarker, ANIM_TYPE_STAND)
    end

    function StartInfectedQuest(player)
        AddJournalEntry(player, "infected_quest_journal", "ReplaceableTextures\\CommandButtons\\BTNShimmerWeed.blp", GetLocalString("Инфекция", "The Infection"), 5, false)
        AddJournalEntryText(player, "infected_quest_journal", GetConversationText("estrid_infected_start_conv", Estrid, player), false)
        AddJournalEntryObjective(player, "infected_quest_journal", "infected_quest_journal_gloomreed_count", GetLocalString("Мрачный тростник собран: ", "Gloomreed gathered: ") .. "0/10")
        SendQuestMessage(QUEST_REVEALED_STRING .. GetLocalString("Инфекция", "The Infection"), bj_TEXT_DELAY_QUEST)
        StartSound(QUEST_REVEALED_SOUND or bj_questDiscoveredSound)
        EnableGloomreedSpawn()
        GloomreedStage[player] = 1
    end

    function CompleteInfectedQuest(player)
        GloomreedStage[player] = 3
        GiveExpForPlayer(200, player)
        GiveGoldForPlayer(250, player)
        RemoveJournalEntry(player, "infected_quest_journal")
    end

    function InitInfectedOnes()
        GloomreedGathered = {}
        GloomreedLocations = {}
        GloomreedStage = {}
        GloomreedTimer = CreateTimer()
        GloomreedId = FourCC("I04Y")

            for i = 1, 6 do
                GloomreedGathered[i] = 0
                GloomreedStage[i] = 0
            end

        GloomreedLocations[1] = gg_rct_gloomreed_1
        GloomreedLocations[2] = gg_rct_gloomreed_2
        GloomreedLocations[3] = gg_rct_gloomreed_3

        PickUpItemReactionEx("I04Y", function(trigger_unit)
            local player = GetPlayerId(GetOwningPlayer(trigger_unit)) + 1

                if GloomreedStage[player] == 1 then
                    GloomreedGathered[player] = GloomreedGathered[player] + 1
                    ChangeJournalEntryObjective(player, "infected_quest_journal", "infected_quest_journal_gloomreed_count", GetLocalString("Мрачный тростник собран: ", "Gloomreed gathered: ") .. GloomreedGathered[player] .."/10", GloomreedGathered[player] < 10)
                    if GloomreedGathered[player] >= 10 then
                        GloomreedStage[player] = 2
                        SetJournalEntryObjectiveState(player, "infected_quest_journal", "infected_quest_journal_gloomreed_count", JOURNAL_OBJECTIVE_STATE_DONE, true)
                        UnlockInteractiveOptionIdPlayer(Estrid, "estrid_infected_end_conv", player)
                        if GetLocalPlayer() == Player(player - 1) then BlzPlaySpecialEffect(EstridData.questmarker_done, ANIM_TYPE_STAND) end
                    end
                end

        end)

    end

end